//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("NewPlatform.Flexberry.ServiceBus.ClientTools")]
[assembly: System.Reflection.AssemblyDescription("Flexberry Service Bus ClientTools")]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Reflection.AssemblyCompany("New Platform Ltd.")]
[assembly: System.Reflection.AssemblyProduct("Flexberry Service Bus")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © New Platform Ltd. 2017.")]
[assembly: System.Reflection.AssemblyTrademark("Flexberry")]
[assembly: System.Reflection.AssemblyCulture("")]
[assembly: System.Reflection.AssemblyVersion("1.0.0.1")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.1")]

[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("NewPlatform.Flexberry.ServiceBus, PublicKey=002400000480000094000000060200000024000052534131000400000100010051190a2b935f63afdba0b92854682d6608a98cb85691a3c154e38966a2a172c339b3b5030451d68ddb6f1eb66b6ba8031690a6bf3a64ef4d2888370bc015ee4e1cca160e885862c31283796a2c45ad32ab1520b92ae752b3c7140ffbc6456ed99fbcfff259c867f0c080b3fa41ded248e385ff91d4bd0ce897710bef102530b1")]
