//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ServiceBus
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    using ICSSoft.STORMNET.Business.Audit.Objects;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Bus.
    /// </summary>
    // *** Start programmer edit section *** (Bus CustomAttributes)

    // *** End programmer edit section *** (Bus CustomAttributes)
    [ClassStorage("Шина")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.@this)]
    [View("AuditView", new string[] {
            "ManagerAddress as \'Адрес интерфейса управления шиной\'",
            "ID as \'ID\'",
            "Name as \'Наименование\'",
            "Address as \'Адрес\'",
            "DnsIdentity as \'DnsIdentity\'",
            "Description as \'Описание\'"})]
    [AssociatedDetailViewAttribute("AuditView", "Subscriptions", "AuditView", true, "", "Subscriptions", true, new string[] {
            ""})]
    [View("EditView", new string[] {
            "ID as \'ID\'",
            "Name as \'Наименование\'",
            "ManagerAddress as \'Адрес интерфейса управления шиной\'",
            "Address as \'Адрес\'",
            "DnsIdentity as \'DnsIdentity\'",
            "Description as \'Описание\'"})]
    [AssociatedDetailViewAttribute("EditView", "Subscriptions", "DetailView", true, "", "Subscriptions", true, new string[] {
            ""})]
    [View("ListView", new string[] {
            "ID as \'ID\'",
            "Name as \'Наименование\'",
            "ManagerAddress as \'Адрес интерфейса управления шиной\'"})]
    public class Bus : NewPlatform.Flexberry.ServiceBus.Client, IDataObjectWithAuditFields
    {
        
        private string fManagerAddress;
        
        // *** Start programmer edit section *** (Bus CustomMembers)

        // *** End programmer edit section *** (Bus CustomMembers)

        
        /// <summary>
        /// ManagerAddress.
        /// </summary>
        // *** Start programmer edit section *** (Bus.ManagerAddress CustomAttributes)

        // *** End programmer edit section *** (Bus.ManagerAddress CustomAttributes)
        [PropertyStorage("InteropАдрес")]
        [StrLen(255)]
        [NotNull()]
        public virtual string ManagerAddress
        {
            get
            {
                // *** Start programmer edit section *** (Bus.ManagerAddress Get start)

                // *** End programmer edit section *** (Bus.ManagerAddress Get start)
                string result = this.fManagerAddress;
                // *** Start programmer edit section *** (Bus.ManagerAddress Get end)

                // *** End programmer edit section *** (Bus.ManagerAddress Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Bus.ManagerAddress Set start)

                // *** End programmer edit section *** (Bus.ManagerAddress Set start)
                this.fManagerAddress = value;
                // *** Start programmer edit section *** (Bus.ManagerAddress Set end)

                // *** End programmer edit section *** (Bus.ManagerAddress Set end)
            }
        }
        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (Bus.CreateTime CustomAttributes)

        // *** End programmer edit section *** (Bus.CreateTime CustomAttributes)
        public override System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (Bus.CreateTime Get start)

                // *** End programmer edit section *** (Bus.CreateTime Get start)
                System.Nullable<System.DateTime> result = base.CreateTime;
                // *** Start programmer edit section *** (Bus.CreateTime Get end)

                // *** End programmer edit section *** (Bus.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Bus.CreateTime Set start)

                // *** End programmer edit section *** (Bus.CreateTime Set start)
                base.CreateTime = value;
                // *** Start programmer edit section *** (Bus.CreateTime Set end)

                // *** End programmer edit section *** (Bus.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (Bus.Creator CustomAttributes)

        // *** End programmer edit section *** (Bus.Creator CustomAttributes)
        [StrLen(255)]
        public override string Creator
        {
            get
            {
                // *** Start programmer edit section *** (Bus.Creator Get start)

                // *** End programmer edit section *** (Bus.Creator Get start)
                string result = base.Creator;
                // *** Start programmer edit section *** (Bus.Creator Get end)

                // *** End programmer edit section *** (Bus.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Bus.Creator Set start)

                // *** End programmer edit section *** (Bus.Creator Set start)
                base.Creator = value;
                // *** Start programmer edit section *** (Bus.Creator Set end)

                // *** End programmer edit section *** (Bus.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (Bus.EditTime CustomAttributes)

        // *** End programmer edit section *** (Bus.EditTime CustomAttributes)
        public override System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (Bus.EditTime Get start)

                // *** End programmer edit section *** (Bus.EditTime Get start)
                System.Nullable<System.DateTime> result = base.EditTime;
                // *** Start programmer edit section *** (Bus.EditTime Get end)

                // *** End programmer edit section *** (Bus.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Bus.EditTime Set start)

                // *** End programmer edit section *** (Bus.EditTime Set start)
                base.EditTime = value;
                // *** Start programmer edit section *** (Bus.EditTime Set end)

                // *** End programmer edit section *** (Bus.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (Bus.Editor CustomAttributes)

        // *** End programmer edit section *** (Bus.Editor CustomAttributes)
        [StrLen(255)]
        public override string Editor
        {
            get
            {
                // *** Start programmer edit section *** (Bus.Editor Get start)

                // *** End programmer edit section *** (Bus.Editor Get start)
                string result = base.Editor;
                // *** Start programmer edit section *** (Bus.Editor Get end)

                // *** End programmer edit section *** (Bus.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Bus.Editor Set start)

                // *** End programmer edit section *** (Bus.Editor Set start)
                base.Editor = value;
                // *** Start programmer edit section *** (Bus.Editor Set end)

                // *** End programmer edit section *** (Bus.Editor Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(NewPlatform.Flexberry.ServiceBus.Bus));
                }
            }
            
            /// <summary>
            /// "EditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View EditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("EditView", typeof(NewPlatform.Flexberry.ServiceBus.Bus));
                }
            }
            
            /// <summary>
            /// "ListView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ListView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ListView", typeof(NewPlatform.Flexberry.ServiceBus.Bus));
                }
            }
        }
        
        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {
            
            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;
            
            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;
            
            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";
            
            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";
            
            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;
            
            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;
            
            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;
            
            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;
            
            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;
            
            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }
}
