//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ServiceBus
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    using ICSSoft.STORMNET.Business.Audit.Objects;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// StatisticsSetting.
    /// </summary>
    // *** Start programmer edit section *** (StatisticsSetting CustomAttributes)

    // *** End programmer edit section *** (StatisticsSetting CustomAttributes)
    [ClassStorage("StatSetting")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.@this)]
    [View("AuditView", new string[] {
            "Subscription as \'Подписка\'",
            "Subscription.Description as \'Описание\'"})]
    [AssociatedDetailViewAttribute("AuditView", "StatisticsCompressionSetting", "AuditView", true, "", "Statistics compression setting", true, new string[] {
            ""})]
    [View("CompressView", new string[] {
            "Subscription as \'Подписка\'",
            "Subscription.Client as \'Клиент\'",
            "Subscription.MessageType as \'Тип сообщения\'"})]
    [AssociatedDetailViewAttribute("CompressView", "StatisticsCompressionSetting", "CompressView", true, "", "", true, new string[] {
            ""})]
    [View("EditView", new string[] {
            "Subscription as \'Подписка\'",
            "Subscription.Description",
            "Subscription.Client",
            "Subscription.Client.ID",
            "Subscription.Client.Name",
            "Subscription.MessageType",
            "Subscription.MessageType.ID",
            "Subscription.MessageType.Name"}, Hidden=new string[] {
            "Subscription.Description",
            "Subscription.Client",
            "Subscription.Client.ID",
            "Subscription.Client.Name",
            "Subscription.MessageType",
            "Subscription.MessageType.ID",
            "Subscription.MessageType.Name"})]
    [AssociatedDetailViewAttribute("EditView", "StatisticsCompressionSetting", "DetailView", true, "", "Statistics compression settings", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("EditView", "StatisticsRecord", "DetailView", true, "", "Statistics records", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("EditView", "Subscription", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Description")]
    [View("ListView", new string[] {
            "Subscription",
            "Subscription.Description as \'Подписка\'",
            "Subscription.Client",
            "Subscription.Client.ID",
            "Subscription.Client.Name",
            "Subscription.MessageType",
            "Subscription.MessageType.ID",
            "Subscription.MessageType.Name"}, Hidden=new string[] {
            "Subscription",
            "Subscription.Client",
            "Subscription.Client.ID",
            "Subscription.Client.Name",
            "Subscription.MessageType",
            "Subscription.MessageType.ID",
            "Subscription.MessageType.Name"})]
    public class StatisticsSetting : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields
    {
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        private NewPlatform.Flexberry.ServiceBus.Subscription fSubscription;
        
        private NewPlatform.Flexberry.ServiceBus.DetailArrayOfStatisticsCompressionSetting fStatisticsCompressionSetting;
        
        private NewPlatform.Flexberry.ServiceBus.DetailArrayOfStatisticsRecord fStatisticsRecord;
        
        // *** Start programmer edit section *** (StatisticsSetting CustomMembers)

        // *** End programmer edit section *** (StatisticsSetting CustomMembers)

        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (StatisticsSetting.CreateTime CustomAttributes)

        // *** End programmer edit section *** (StatisticsSetting.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (StatisticsSetting.CreateTime Get start)

                // *** End programmer edit section *** (StatisticsSetting.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (StatisticsSetting.CreateTime Get end)

                // *** End programmer edit section *** (StatisticsSetting.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (StatisticsSetting.CreateTime Set start)

                // *** End programmer edit section *** (StatisticsSetting.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (StatisticsSetting.CreateTime Set end)

                // *** End programmer edit section *** (StatisticsSetting.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (StatisticsSetting.Creator CustomAttributes)

        // *** End programmer edit section *** (StatisticsSetting.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (StatisticsSetting.Creator Get start)

                // *** End programmer edit section *** (StatisticsSetting.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (StatisticsSetting.Creator Get end)

                // *** End programmer edit section *** (StatisticsSetting.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (StatisticsSetting.Creator Set start)

                // *** End programmer edit section *** (StatisticsSetting.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (StatisticsSetting.Creator Set end)

                // *** End programmer edit section *** (StatisticsSetting.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (StatisticsSetting.EditTime CustomAttributes)

        // *** End programmer edit section *** (StatisticsSetting.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (StatisticsSetting.EditTime Get start)

                // *** End programmer edit section *** (StatisticsSetting.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (StatisticsSetting.EditTime Get end)

                // *** End programmer edit section *** (StatisticsSetting.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (StatisticsSetting.EditTime Set start)

                // *** End programmer edit section *** (StatisticsSetting.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (StatisticsSetting.EditTime Set end)

                // *** End programmer edit section *** (StatisticsSetting.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (StatisticsSetting.Editor CustomAttributes)

        // *** End programmer edit section *** (StatisticsSetting.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (StatisticsSetting.Editor Get start)

                // *** End programmer edit section *** (StatisticsSetting.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (StatisticsSetting.Editor Get end)

                // *** End programmer edit section *** (StatisticsSetting.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (StatisticsSetting.Editor Set start)

                // *** End programmer edit section *** (StatisticsSetting.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (StatisticsSetting.Editor Set end)

                // *** End programmer edit section *** (StatisticsSetting.Editor Set end)
            }
        }
        
        /// <summary>
        /// StatisticsSetting.
        /// </summary>
        // *** Start programmer edit section *** (StatisticsSetting.Subscription CustomAttributes)

        // *** End programmer edit section *** (StatisticsSetting.Subscription CustomAttributes)
        [PropertyStorage(new string[] {
                "Подписка"})]
        public virtual NewPlatform.Flexberry.ServiceBus.Subscription Subscription
        {
            get
            {
                // *** Start programmer edit section *** (StatisticsSetting.Subscription Get start)

                // *** End programmer edit section *** (StatisticsSetting.Subscription Get start)
                NewPlatform.Flexberry.ServiceBus.Subscription result = this.fSubscription;
                // *** Start programmer edit section *** (StatisticsSetting.Subscription Get end)

                // *** End programmer edit section *** (StatisticsSetting.Subscription Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (StatisticsSetting.Subscription Set start)

                // *** End programmer edit section *** (StatisticsSetting.Subscription Set start)
                this.fSubscription = value;
                // *** Start programmer edit section *** (StatisticsSetting.Subscription Set end)

                // *** End programmer edit section *** (StatisticsSetting.Subscription Set end)
            }
        }
        
        /// <summary>
        /// StatisticsSetting.
        /// </summary>
        // *** Start programmer edit section *** (StatisticsSetting.StatisticsCompressionSetting CustomAttributes)

        // *** End programmer edit section *** (StatisticsSetting.StatisticsCompressionSetting CustomAttributes)
        public virtual NewPlatform.Flexberry.ServiceBus.DetailArrayOfStatisticsCompressionSetting StatisticsCompressionSetting
        {
            get
            {
                // *** Start programmer edit section *** (StatisticsSetting.StatisticsCompressionSetting Get start)

                // *** End programmer edit section *** (StatisticsSetting.StatisticsCompressionSetting Get start)
                if ((this.fStatisticsCompressionSetting == null))
                {
                    this.fStatisticsCompressionSetting = new NewPlatform.Flexberry.ServiceBus.DetailArrayOfStatisticsCompressionSetting(this);
                }
                NewPlatform.Flexberry.ServiceBus.DetailArrayOfStatisticsCompressionSetting result = this.fStatisticsCompressionSetting;
                // *** Start programmer edit section *** (StatisticsSetting.StatisticsCompressionSetting Get end)

                // *** End programmer edit section *** (StatisticsSetting.StatisticsCompressionSetting Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (StatisticsSetting.StatisticsCompressionSetting Set start)

                // *** End programmer edit section *** (StatisticsSetting.StatisticsCompressionSetting Set start)
                this.fStatisticsCompressionSetting = value;
                // *** Start programmer edit section *** (StatisticsSetting.StatisticsCompressionSetting Set end)

                // *** End programmer edit section *** (StatisticsSetting.StatisticsCompressionSetting Set end)
            }
        }
        
        /// <summary>
        /// StatisticsSetting.
        /// </summary>
        // *** Start programmer edit section *** (StatisticsSetting.StatisticsRecord CustomAttributes)

        // *** End programmer edit section *** (StatisticsSetting.StatisticsRecord CustomAttributes)
        public virtual NewPlatform.Flexberry.ServiceBus.DetailArrayOfStatisticsRecord StatisticsRecord
        {
            get
            {
                // *** Start programmer edit section *** (StatisticsSetting.StatisticsRecord Get start)

                // *** End programmer edit section *** (StatisticsSetting.StatisticsRecord Get start)
                if ((this.fStatisticsRecord == null))
                {
                    this.fStatisticsRecord = new NewPlatform.Flexberry.ServiceBus.DetailArrayOfStatisticsRecord(this);
                }
                NewPlatform.Flexberry.ServiceBus.DetailArrayOfStatisticsRecord result = this.fStatisticsRecord;
                // *** Start programmer edit section *** (StatisticsSetting.StatisticsRecord Get end)

                // *** End programmer edit section *** (StatisticsSetting.StatisticsRecord Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (StatisticsSetting.StatisticsRecord Set start)

                // *** End programmer edit section *** (StatisticsSetting.StatisticsRecord Set start)
                this.fStatisticsRecord = value;
                // *** Start programmer edit section *** (StatisticsSetting.StatisticsRecord Set end)

                // *** End programmer edit section *** (StatisticsSetting.StatisticsRecord Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(NewPlatform.Flexberry.ServiceBus.StatisticsSetting));
                }
            }
            
            /// <summary>
            /// "CompressView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CompressView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CompressView", typeof(NewPlatform.Flexberry.ServiceBus.StatisticsSetting));
                }
            }
            
            /// <summary>
            /// "EditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View EditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("EditView", typeof(NewPlatform.Flexberry.ServiceBus.StatisticsSetting));
                }
            }
            
            /// <summary>
            /// "ListView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ListView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ListView", typeof(NewPlatform.Flexberry.ServiceBus.StatisticsSetting));
                }
            }
        }
        
        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {
            
            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;
            
            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;
            
            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";
            
            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";
            
            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;
            
            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;
            
            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;
            
            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;
            
            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;
            
            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }
}
