//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ServiceBus
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    using ICSSoft.STORMNET.Business.Audit.Objects;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// StatisticsMonitor.
    /// </summary>
    // *** Start programmer edit section *** (StatisticsMonitor CustomAttributes)

    // *** End programmer edit section *** (StatisticsMonitor CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.@this)]
    [View("AuditView", new string[] {
            "Owner as \'Owner\'",
            "Name as \'Name\'",
            "Public as \'Public\'"})]
    [AssociatedDetailViewAttribute("AuditView", "SubscriptionStatisticsMonitor", "AuditView", true, "", "Subscription statistics monitor", true, new string[] {
            ""})]
    [View("EditView", new string[] {
            "Owner",
            "Name as \'Name\'",
            "Public as \'Public\'"}, Hidden=new string[] {
            "Owner"})]
    [AssociatedDetailViewAttribute("EditView", "SubscriptionStatisticsMonitor", "DetailView", true, "", "Subscriptions statistics monitor", true, new string[] {
            ""})]
    [View("ListView", new string[] {
            "Owner as \'Owner\'",
            "Name as \'Name\'",
            "Public as \'Public\'"}, Hidden=new string[] {
            "Owner"})]
    public class StatisticsMonitor : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields
    {
        
        private string fOwner;
        
        private string fName;
        
        private bool fPublic;
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        private NewPlatform.Flexberry.ServiceBus.DetailArrayOfSubscriptionStatisticsMonitor fSubscriptionStatisticsMonitor;
        
        // *** Start programmer edit section *** (StatisticsMonitor CustomMembers)

        // *** End programmer edit section *** (StatisticsMonitor CustomMembers)

        
        /// <summary>
        /// Owner.
        /// </summary>
        // *** Start programmer edit section *** (StatisticsMonitor.Owner CustomAttributes)

        // *** End programmer edit section *** (StatisticsMonitor.Owner CustomAttributes)
        [PropertyStorage("Логин")]
        [StrLen(255)]
        public virtual string Owner
        {
            get
            {
                // *** Start programmer edit section *** (StatisticsMonitor.Owner Get start)

                // *** End programmer edit section *** (StatisticsMonitor.Owner Get start)
                string result = this.fOwner;
                // *** Start programmer edit section *** (StatisticsMonitor.Owner Get end)

                // *** End programmer edit section *** (StatisticsMonitor.Owner Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (StatisticsMonitor.Owner Set start)

                // *** End programmer edit section *** (StatisticsMonitor.Owner Set start)
                this.fOwner = value;
                // *** Start programmer edit section *** (StatisticsMonitor.Owner Set end)

                // *** End programmer edit section *** (StatisticsMonitor.Owner Set end)
            }
        }
        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (StatisticsMonitor.Name CustomAttributes)

        // *** End programmer edit section *** (StatisticsMonitor.Name CustomAttributes)
        [PropertyStorage("Наименование")]
        [StrLen(255)]
        [NotNull()]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (StatisticsMonitor.Name Get start)

                // *** End programmer edit section *** (StatisticsMonitor.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (StatisticsMonitor.Name Get end)

                // *** End programmer edit section *** (StatisticsMonitor.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (StatisticsMonitor.Name Set start)

                // *** End programmer edit section *** (StatisticsMonitor.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (StatisticsMonitor.Name Set end)

                // *** End programmer edit section *** (StatisticsMonitor.Name Set end)
            }
        }
        
        /// <summary>
        /// Public.
        /// </summary>
        // *** Start programmer edit section *** (StatisticsMonitor.Public CustomAttributes)

        // *** End programmer edit section *** (StatisticsMonitor.Public CustomAttributes)
        [PropertyStorage("ДоступенДругимПользователям")]
        public virtual bool Public
        {
            get
            {
                // *** Start programmer edit section *** (StatisticsMonitor.Public Get start)

                // *** End programmer edit section *** (StatisticsMonitor.Public Get start)
                bool result = this.fPublic;
                // *** Start programmer edit section *** (StatisticsMonitor.Public Get end)

                // *** End programmer edit section *** (StatisticsMonitor.Public Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (StatisticsMonitor.Public Set start)

                // *** End programmer edit section *** (StatisticsMonitor.Public Set start)
                this.fPublic = value;
                // *** Start programmer edit section *** (StatisticsMonitor.Public Set end)

                // *** End programmer edit section *** (StatisticsMonitor.Public Set end)
            }
        }
        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (StatisticsMonitor.CreateTime CustomAttributes)

        // *** End programmer edit section *** (StatisticsMonitor.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (StatisticsMonitor.CreateTime Get start)

                // *** End programmer edit section *** (StatisticsMonitor.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (StatisticsMonitor.CreateTime Get end)

                // *** End programmer edit section *** (StatisticsMonitor.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (StatisticsMonitor.CreateTime Set start)

                // *** End programmer edit section *** (StatisticsMonitor.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (StatisticsMonitor.CreateTime Set end)

                // *** End programmer edit section *** (StatisticsMonitor.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (StatisticsMonitor.Creator CustomAttributes)

        // *** End programmer edit section *** (StatisticsMonitor.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (StatisticsMonitor.Creator Get start)

                // *** End programmer edit section *** (StatisticsMonitor.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (StatisticsMonitor.Creator Get end)

                // *** End programmer edit section *** (StatisticsMonitor.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (StatisticsMonitor.Creator Set start)

                // *** End programmer edit section *** (StatisticsMonitor.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (StatisticsMonitor.Creator Set end)

                // *** End programmer edit section *** (StatisticsMonitor.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (StatisticsMonitor.EditTime CustomAttributes)

        // *** End programmer edit section *** (StatisticsMonitor.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (StatisticsMonitor.EditTime Get start)

                // *** End programmer edit section *** (StatisticsMonitor.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (StatisticsMonitor.EditTime Get end)

                // *** End programmer edit section *** (StatisticsMonitor.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (StatisticsMonitor.EditTime Set start)

                // *** End programmer edit section *** (StatisticsMonitor.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (StatisticsMonitor.EditTime Set end)

                // *** End programmer edit section *** (StatisticsMonitor.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (StatisticsMonitor.Editor CustomAttributes)

        // *** End programmer edit section *** (StatisticsMonitor.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (StatisticsMonitor.Editor Get start)

                // *** End programmer edit section *** (StatisticsMonitor.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (StatisticsMonitor.Editor Get end)

                // *** End programmer edit section *** (StatisticsMonitor.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (StatisticsMonitor.Editor Set start)

                // *** End programmer edit section *** (StatisticsMonitor.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (StatisticsMonitor.Editor Set end)

                // *** End programmer edit section *** (StatisticsMonitor.Editor Set end)
            }
        }
        
        /// <summary>
        /// StatisticsMonitor.
        /// </summary>
        // *** Start programmer edit section *** (StatisticsMonitor.SubscriptionStatisticsMonitor CustomAttributes)

        // *** End programmer edit section *** (StatisticsMonitor.SubscriptionStatisticsMonitor CustomAttributes)
        public virtual NewPlatform.Flexberry.ServiceBus.DetailArrayOfSubscriptionStatisticsMonitor SubscriptionStatisticsMonitor
        {
            get
            {
                // *** Start programmer edit section *** (StatisticsMonitor.SubscriptionStatisticsMonitor Get start)

                // *** End programmer edit section *** (StatisticsMonitor.SubscriptionStatisticsMonitor Get start)
                if ((this.fSubscriptionStatisticsMonitor == null))
                {
                    this.fSubscriptionStatisticsMonitor = new NewPlatform.Flexberry.ServiceBus.DetailArrayOfSubscriptionStatisticsMonitor(this);
                }
                NewPlatform.Flexberry.ServiceBus.DetailArrayOfSubscriptionStatisticsMonitor result = this.fSubscriptionStatisticsMonitor;
                // *** Start programmer edit section *** (StatisticsMonitor.SubscriptionStatisticsMonitor Get end)

                // *** End programmer edit section *** (StatisticsMonitor.SubscriptionStatisticsMonitor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (StatisticsMonitor.SubscriptionStatisticsMonitor Set start)

                // *** End programmer edit section *** (StatisticsMonitor.SubscriptionStatisticsMonitor Set start)
                this.fSubscriptionStatisticsMonitor = value;
                // *** Start programmer edit section *** (StatisticsMonitor.SubscriptionStatisticsMonitor Set end)

                // *** End programmer edit section *** (StatisticsMonitor.SubscriptionStatisticsMonitor Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(NewPlatform.Flexberry.ServiceBus.StatisticsMonitor));
                }
            }
            
            /// <summary>
            /// "EditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View EditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("EditView", typeof(NewPlatform.Flexberry.ServiceBus.StatisticsMonitor));
                }
            }
            
            /// <summary>
            /// "ListView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ListView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ListView", typeof(NewPlatform.Flexberry.ServiceBus.StatisticsMonitor));
                }
            }
        }
        
        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {
            
            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;
            
            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;
            
            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";
            
            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";
            
            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;
            
            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;
            
            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;
            
            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;
            
            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;
            
            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }
}
