//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ServiceBus
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// StatisticsInterval.
    /// </summary>
    // *** Start programmer edit section *** (StatisticsInterval CustomAttributes)

    // *** End programmer edit section *** (StatisticsInterval CustomAttributes)
    public enum StatisticsInterval
    {

        /// <summary>
        ///
        /// </summary>
        // *** Start programmer edit section *** (StatisticsInterval.OneSecond CustomAttributes)

        // *** End programmer edit section *** (StatisticsInterval.OneSecond CustomAttributes)
        [Caption("One second")]
        OneSecond,

        /// <summary>
        ///
        /// </summary>
        // *** Start programmer edit section *** (StatisticsInterval.TenSeconds CustomAttributes)

        // *** End programmer edit section *** (StatisticsInterval.TenSeconds CustomAttributes)
        [Caption("Ten seconds")]
        TenSeconds,

        /// <summary>
        ///
        /// </summary>
        // *** Start programmer edit section *** (StatisticsInterval.OneMinute CustomAttributes)

        // *** End programmer edit section *** (StatisticsInterval.OneMinute CustomAttributes)
        [Caption("One minute")]
        OneMinute,

        /// <summary>
        ///
        /// </summary>
        // *** Start programmer edit section *** (StatisticsInterval.FiveMinutes CustomAttributes)

        // *** End programmer edit section *** (StatisticsInterval.FiveMinutes CustomAttributes)
        [Caption("Five minutes")]
        FiveMinutes,

        /// <summary>
        ///
        /// </summary>
        // *** Start programmer edit section *** (StatisticsInterval.TenMinutes CustomAttributes)

        // *** End programmer edit section *** (StatisticsInterval.TenMinutes CustomAttributes)
        [Caption("Ten minutes")]
        TenMinutes,

        /// <summary>
        ///
        /// </summary>
        // *** Start programmer edit section *** (StatisticsInterval.HalfAnHour CustomAttributes)

        // *** End programmer edit section *** (StatisticsInterval.HalfAnHour CustomAttributes)
        [Caption("Half an hour")]
        HalfAnHour,

        /// <summary>
        ///
        /// </summary>
        // *** Start programmer edit section *** (StatisticsInterval.Hour CustomAttributes)

        // *** End programmer edit section *** (StatisticsInterval.Hour CustomAttributes)
        [Caption("Hour")]
        Hour,

        /// <summary>
        ///
        /// </summary>
        // *** Start programmer edit section *** (StatisticsInterval.Day CustomAttributes)

        // *** End programmer edit section *** (StatisticsInterval.Day CustomAttributes)
        [Caption("Day")]
        Day,

        /// <summary>
        ///
        /// </summary>
        // *** Start programmer edit section *** (StatisticsInterval.Month CustomAttributes)

        // *** End programmer edit section *** (StatisticsInterval.Month CustomAttributes)
        [Caption("Month")]
        Month,

        /// <summary>
        ///
        /// </summary>
        // *** Start programmer edit section *** (StatisticsInterval.Quarter CustomAttributes)

        // *** End programmer edit section *** (StatisticsInterval.Quarter CustomAttributes)
        [Caption("Quarter")]
        Quarter,

        /// <summary>
        ///
        /// </summary>
        // *** Start programmer edit section *** (StatisticsInterval.Year CustomAttributes)

        // *** End programmer edit section *** (StatisticsInterval.Year CustomAttributes)
        [Caption("Year")]
        Year,
    }
}
