//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ServiceBus
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// TimeUnit.
    /// </summary>
    // *** Start programmer edit section *** (TimeUnit CustomAttributes)

    // *** End programmer edit section *** (TimeUnit CustomAttributes)
    public enum TimeUnit
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (TimeUnit.Minute CustomAttributes)

        // *** End programmer edit section *** (TimeUnit.Minute CustomAttributes)
        [Caption("Minute")]
        Minute,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (TimeUnit.Hour CustomAttributes)

        // *** End programmer edit section *** (TimeUnit.Hour CustomAttributes)
        [Caption("Hour")]
        Hour,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (TimeUnit.Day CustomAttributes)

        // *** End programmer edit section *** (TimeUnit.Day CustomAttributes)
        [Caption("Day")]
        Day,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (TimeUnit.Month CustomAttributes)

        // *** End programmer edit section *** (TimeUnit.Month CustomAttributes)
        [Caption("Month")]
        Month,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (TimeUnit.Year CustomAttributes)

        // *** End programmer edit section *** (TimeUnit.Year CustomAttributes)
        [Caption("Year")]
        Year,
    }
}
