//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ServiceBus
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)
    using System.Runtime.Serialization;
    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Основная информация о сообщении для отправки из шины.
    /// </summary>
    // *** Start programmer edit section *** (MessageInfoFromESB CustomAttributes)
    [DataContract(Namespace = "http://schemas.datacontract.org/2004/07/IIS.Persona.ServiceBus.Objects")]
    // *** End programmer edit section *** (MessageInfoFromESB CustomAttributes)
    public class MessageInfoFromESB
    {
        
        private string fId;
        
        private string fMessageTypeID;
        
        private int fPriority = 0;
        
        private System.DateTime fMessageFormingTime;
        
        // *** Start programmer edit section *** (MessageInfoFromESB CustomMembers)

        // *** End programmer edit section *** (MessageInfoFromESB CustomMembers)

        
        /// <summary>
        /// Уникальный идентификатор сообщения.
        /// </summary>
        // *** Start programmer edit section *** (MessageInfoFromESB.Id CustomAttributes)
        [DataMember]
        // *** End programmer edit section *** (MessageInfoFromESB.Id CustomAttributes)
        public virtual string Id
        {
            get
            {
                // *** Start programmer edit section *** (MessageInfoFromESB.Id Get start)

                // *** End programmer edit section *** (MessageInfoFromESB.Id Get start)
                string result = this.fId;
                // *** Start programmer edit section *** (MessageInfoFromESB.Id Get end)

                // *** End programmer edit section *** (MessageInfoFromESB.Id Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MessageInfoFromESB.Id Set start)

                // *** End programmer edit section *** (MessageInfoFromESB.Id Set start)
                this.fId = value;
                // *** Start programmer edit section *** (MessageInfoFromESB.Id Set end)

                // *** End programmer edit section *** (MessageInfoFromESB.Id Set end)
            }
        }
        
        /// <summary>
        /// Идентификатор типа сообщения.
        /// </summary>
        // *** Start programmer edit section *** (MessageInfoFromESB.MessageTypeID CustomAttributes)
        [DataMember]
        // *** End programmer edit section *** (MessageInfoFromESB.MessageTypeID CustomAttributes)
        public virtual string MessageTypeID
        {
            get
            {
                // *** Start programmer edit section *** (MessageInfoFromESB.MessageTypeID Get start)

                // *** End programmer edit section *** (MessageInfoFromESB.MessageTypeID Get start)
                string result = this.fMessageTypeID;
                // *** Start programmer edit section *** (MessageInfoFromESB.MessageTypeID Get end)

                // *** End programmer edit section *** (MessageInfoFromESB.MessageTypeID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MessageInfoFromESB.MessageTypeID Set start)

                // *** End programmer edit section *** (MessageInfoFromESB.MessageTypeID Set start)
                this.fMessageTypeID = value;
                // *** Start programmer edit section *** (MessageInfoFromESB.MessageTypeID Set end)

                // *** End programmer edit section *** (MessageInfoFromESB.MessageTypeID Set end)
            }
        }
        
        /// <summary>
        /// Приоритет сообщения.
        /// </summary>
        // *** Start programmer edit section *** (MessageInfoFromESB.Priority CustomAttributes)
        [DataMember]
        // *** End programmer edit section *** (MessageInfoFromESB.Priority CustomAttributes)
        public virtual int Priority
        {
            get
            {
                // *** Start programmer edit section *** (MessageInfoFromESB.Priority Get start)

                // *** End programmer edit section *** (MessageInfoFromESB.Priority Get start)
                int result = this.fPriority;
                // *** Start programmer edit section *** (MessageInfoFromESB.Priority Get end)

                // *** End programmer edit section *** (MessageInfoFromESB.Priority Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MessageInfoFromESB.Priority Set start)

                // *** End programmer edit section *** (MessageInfoFromESB.Priority Set start)
                this.fPriority = value;
                // *** Start programmer edit section *** (MessageInfoFromESB.Priority Set end)

                // *** End programmer edit section *** (MessageInfoFromESB.Priority Set end)
            }
        }
        
        /// <summary>
        /// Время формирования сообщения.
        /// </summary>
        // *** Start programmer edit section *** (MessageInfoFromESB.MessageFormingTime CustomAttributes)
        [DataMember]
        // *** End programmer edit section *** (MessageInfoFromESB.MessageFormingTime CustomAttributes)
        public virtual System.DateTime MessageFormingTime
        {
            get
            {
                // *** Start programmer edit section *** (MessageInfoFromESB.MessageFormingTime Get start)

                // *** End programmer edit section *** (MessageInfoFromESB.MessageFormingTime Get start)
                System.DateTime result = this.fMessageFormingTime;
                // *** Start programmer edit section *** (MessageInfoFromESB.MessageFormingTime Get end)

                // *** End programmer edit section *** (MessageInfoFromESB.MessageFormingTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MessageInfoFromESB.MessageFormingTime Set start)

                // *** End programmer edit section *** (MessageInfoFromESB.MessageFormingTime Set start)
                this.fMessageFormingTime = value;
                // *** Start programmer edit section *** (MessageInfoFromESB.MessageFormingTime Set end)

                // *** End programmer edit section *** (MessageInfoFromESB.MessageFormingTime Set end)
            }
        }
    }
}
