// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NewPlatform.Flexberry.ServiceBus.IntegratedTests.Components.SendingManager.RequestTemplates
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Work.NET\GitHub\NewPlatform.Flexberry.ServiceBus\NewPlatform.Flexberry.ServiceBus.IntegratedTests\Components\SendingManager\RequestTemplates\WebRequestTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class WebRequestTemplate : WebRequestTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"\s*
<s:Envelope xmlns:s=""http://schemas.xmlsoap.org/soap/envelope/"">\s*
<s:Header>\s*
<headerName xmlns=""http://localhost:2525/Message"">headerValue</headerName>\s*
</s:Header>\s*
<s:Body>\s*
<AcceptMessage xmlns=""http://tempuri.org/"">\s*
<msg xmlns:a=""http://schemas.datacontract.org/2004/07/IIS.Persona.ServiceBus.Objects"" xmlns:i=""http://www.w3.org/2001/XMLSchema-instance"">\s*
");
            
            #line 9 "C:\Work.NET\GitHub\NewPlatform.Flexberry.ServiceBus\NewPlatform.Flexberry.ServiceBus.IntegratedTests\Components\SendingManager\RequestTemplates\WebRequestTemplate.tt"
if (Model.Attachment == null) {
            
            #line default
            #line hidden
            this.Write("<a:Attachment/>\\s*\r\n");
            
            #line 11 "C:\Work.NET\GitHub\NewPlatform.Flexberry.ServiceBus\NewPlatform.Flexberry.ServiceBus.IntegratedTests\Components\SendingManager\RequestTemplates\WebRequestTemplate.tt"
} else {
            
            #line default
            #line hidden
            this.Write("<a:Attachment>");
            
            #line 12 "C:\Work.NET\GitHub\NewPlatform.Flexberry.ServiceBus\NewPlatform.Flexberry.ServiceBus.IntegratedTests\Components\SendingManager\RequestTemplates\WebRequestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Attachment));
            
            #line default
            #line hidden
            this.Write("</a:Attachment>\\s*\r\n");
            
            #line 13 "C:\Work.NET\GitHub\NewPlatform.Flexberry.ServiceBus\NewPlatform.Flexberry.ServiceBus.IntegratedTests\Components\SendingManager\RequestTemplates\WebRequestTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("<a:Body>");
            
            #line 14 "C:\Work.NET\GitHub\NewPlatform.Flexberry.ServiceBus\NewPlatform.Flexberry.ServiceBus.IntegratedTests\Components\SendingManager\RequestTemplates\WebRequestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Body));
            
            #line default
            #line hidden
            this.Write("</a:Body>\\s*\r\n");
            
            #line 15 "C:\Work.NET\GitHub\NewPlatform.Flexberry.ServiceBus\NewPlatform.Flexberry.ServiceBus.IntegratedTests\Components\SendingManager\RequestTemplates\WebRequestTemplate.tt"
if (Model.Group == null) {
            
            #line default
            #line hidden
            this.Write("<a:GroupID i:nil=\"true\"/>\\s*\r\n");
            
            #line 17 "C:\Work.NET\GitHub\NewPlatform.Flexberry.ServiceBus\NewPlatform.Flexberry.ServiceBus.IntegratedTests\Components\SendingManager\RequestTemplates\WebRequestTemplate.tt"
} else {
            
            #line default
            #line hidden
            this.Write("<a:GroupID>");
            
            #line 18 "C:\Work.NET\GitHub\NewPlatform.Flexberry.ServiceBus\NewPlatform.Flexberry.ServiceBus.IntegratedTests\Components\SendingManager\RequestTemplates\WebRequestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Group));
            
            #line default
            #line hidden
            this.Write("</a:GroupID>\\s*\r\n");
            
            #line 19 "C:\Work.NET\GitHub\NewPlatform.Flexberry.ServiceBus\NewPlatform.Flexberry.ServiceBus.IntegratedTests\Components\SendingManager\RequestTemplates\WebRequestTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("<a:MessageFormingTime>");
            
            #line 20 "C:\Work.NET\GitHub\NewPlatform.Flexberry.ServiceBus\NewPlatform.Flexberry.ServiceBus.IntegratedTests\Components\SendingManager\RequestTemplates\WebRequestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ReceivingTime.ToString("yyyy-MM-ddTHH:mm:ss.ff")));
            
            #line default
            #line hidden
            this.Write("[\\d]?</a:MessageFormingTime>\\s*\r\n<a:MessageTypeID>");
            
            #line 21 "C:\Work.NET\GitHub\NewPlatform.Flexberry.ServiceBus\NewPlatform.Flexberry.ServiceBus.IntegratedTests\Components\SendingManager\RequestTemplates\WebRequestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.MessageType.ID));
            
            #line default
            #line hidden
            this.Write("</a:MessageTypeID>\\s*\r\n");
            
            #line 22 "C:\Work.NET\GitHub\NewPlatform.Flexberry.ServiceBus\NewPlatform.Flexberry.ServiceBus.IntegratedTests\Components\SendingManager\RequestTemplates\WebRequestTemplate.tt"
if (Model.Sender == null) {
            
            #line default
            #line hidden
            this.Write("<a:SenderName i:nil=\"true\"/>\\s*\r\n");
            
            #line 24 "C:\Work.NET\GitHub\NewPlatform.Flexberry.ServiceBus\NewPlatform.Flexberry.ServiceBus.IntegratedTests\Components\SendingManager\RequestTemplates\WebRequestTemplate.tt"
} else {
            
            #line default
            #line hidden
            this.Write("<a:SenderName>");
            
            #line 25 "C:\Work.NET\GitHub\NewPlatform.Flexberry.ServiceBus\NewPlatform.Flexberry.ServiceBus.IntegratedTests\Components\SendingManager\RequestTemplates\WebRequestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Sender));
            
            #line default
            #line hidden
            this.Write("</a:SenderName>\\s*\r\n");
            
            #line 26 "C:\Work.NET\GitHub\NewPlatform.Flexberry.ServiceBus\NewPlatform.Flexberry.ServiceBus.IntegratedTests\Components\SendingManager\RequestTemplates\WebRequestTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 27 "C:\Work.NET\GitHub\NewPlatform.Flexberry.ServiceBus\NewPlatform.Flexberry.ServiceBus.IntegratedTests\Components\SendingManager\RequestTemplates\WebRequestTemplate.tt"
if (Model.Tags == null) {
            
            #line default
            #line hidden
            this.Write("<a:Tags xmlns:b=\"http://schemas.microsoft.com/2003/10/Serialization/Arrays\"/>\\s*\r" +
                    "\n");
            
            #line 29 "C:\Work.NET\GitHub\NewPlatform.Flexberry.ServiceBus\NewPlatform.Flexberry.ServiceBus.IntegratedTests\Components\SendingManager\RequestTemplates\WebRequestTemplate.tt"
} else {
            
            #line default
            #line hidden
            this.Write("<a:Tags xmlns:b=\"http://schemas.microsoft.com/2003/10/Serialization/Arrays\">\\s*\r\n" +
                    "");
            
            #line 31 "C:\Work.NET\GitHub\NewPlatform.Flexberry.ServiceBus\NewPlatform.Flexberry.ServiceBus.IntegratedTests\Components\SendingManager\RequestTemplates\WebRequestTemplate.tt"
var tags = Model.Tags.Split(new[] { ';' }, StringSplitOptions.RemoveEmptyEntries);
            
            #line default
            #line hidden
            
            #line 32 "C:\Work.NET\GitHub\NewPlatform.Flexberry.ServiceBus\NewPlatform.Flexberry.ServiceBus.IntegratedTests\Components\SendingManager\RequestTemplates\WebRequestTemplate.tt"
foreach (var tag in tags) {
            
            #line default
            #line hidden
            this.Write("<b:KeyValueOfstringstring>\\s*<b:Key>");
            
            #line 33 "C:\Work.NET\GitHub\NewPlatform.Flexberry.ServiceBus\NewPlatform.Flexberry.ServiceBus.IntegratedTests\Components\SendingManager\RequestTemplates\WebRequestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tag.Split(':')[0]));
            
            #line default
            #line hidden
            this.Write("</b:Key>\\s*<b:Value>");
            
            #line 33 "C:\Work.NET\GitHub\NewPlatform.Flexberry.ServiceBus\NewPlatform.Flexberry.ServiceBus.IntegratedTests\Components\SendingManager\RequestTemplates\WebRequestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tag.Split(':')[1]));
            
            #line default
            #line hidden
            this.Write("</b:Value>\\s*</b:KeyValueOfstringstring>\\s*\r\n");
            
            #line 34 "C:\Work.NET\GitHub\NewPlatform.Flexberry.ServiceBus\NewPlatform.Flexberry.ServiceBus.IntegratedTests\Components\SendingManager\RequestTemplates\WebRequestTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("</a:Tags>\\s*\r\n");
            
            #line 36 "C:\Work.NET\GitHub\NewPlatform.Flexberry.ServiceBus\NewPlatform.Flexberry.ServiceBus.IntegratedTests\Components\SendingManager\RequestTemplates\WebRequestTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("</msg>\\s*\r\n</AcceptMessage>\\s*\r\n</s:Body>\\s*\r\n</s:Envelope>\\s*");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class WebRequestTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
