//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ServiceBus.Components
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// IMailScanningServiceSettings.
    /// </summary>
    // *** Start programmer edit section *** (IMailScanningServiceSettings CustomAttributes)

    // *** End programmer edit section *** (IMailScanningServiceSettings CustomAttributes)
    public interface IMailScanningServiceSettings : NewPlatform.Flexberry.ServiceBus.Components.IServiceBusComponent
    {
        
        // *** Start programmer edit section *** (IMailScanningServiceSettings CustomMembers)

        // *** End programmer edit section *** (IMailScanningServiceSettings CustomMembers)

        
        /// <summary>
        /// CheckMail.
        /// </summary>
        // *** Start programmer edit section *** (CheckMail CustomAttributes)

        // *** End programmer edit section *** (CheckMail CustomAttributes)
        bool CheckMail
        {
            get;
            set;
        }
        
        /// <summary>
        /// MailScanPeriod.
        /// </summary>
        // *** Start programmer edit section *** (MailScanPeriod CustomAttributes)

        // *** End programmer edit section *** (MailScanPeriod CustomAttributes)
        int MailScanPeriod
        {
            get;
            set;
        }
    }
}
