//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ServiceBus.Components
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// IMailScanningService.
    /// </summary>
    // *** Start programmer edit section *** (IMailScanningService CustomAttributes)

    // *** End programmer edit section *** (IMailScanningService CustomAttributes)
    public interface IMailScanningService : NewPlatform.Flexberry.ServiceBus.Components.IServiceBusComponent
    {
    }
}
