//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ServiceBus.Components
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// IRerouterService.
    /// </summary>
    // *** Start programmer edit section *** (IRerouterService CustomAttributes)

    // *** End programmer edit section *** (IRerouterService CustomAttributes)
    public interface IRerouterService : NewPlatform.Flexberry.ServiceBus.Components.IServiceBusComponent
    {
        
        // *** Start programmer edit section *** (IRerouterService CustomMembers)

        // *** End programmer edit section *** (IRerouterService CustomMembers)

        
        /// <summary>
        /// Enabled.
        /// </summary>
        // *** Start programmer edit section *** (Enabled CustomAttributes)

        // *** End programmer edit section *** (Enabled CustomAttributes)
        bool Enabled
        {
            get;
            set;
        }
    }
}
