//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ServiceBus.Components
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// IStatisticsCompressorService.
    /// </summary>
    // *** Start programmer edit section *** (IStatisticsCompressorService CustomAttributes)

    // *** End programmer edit section *** (IStatisticsCompressorService CustomAttributes)
    public interface IStatisticsCompressorService : NewPlatform.Flexberry.ServiceBus.Components.IServiceBusComponent
    {
        
        // *** Start programmer edit section *** (IStatisticsCompressorService CustomMembers)

        // *** End programmer edit section *** (IStatisticsCompressorService CustomMembers)

        
        // *** Start programmer edit section *** (IStatisticsCompressorService.CompressStatistics CustomAttributes)

        // *** End programmer edit section *** (IStatisticsCompressorService.CompressStatistics CustomAttributes)
        void CompressStatistics();
    }
}
