//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ServiceBus.Components
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// IStatisticsSettings.
    /// </summary>
    // *** Start programmer edit section *** (IStatisticsSettings CustomAttributes)

    // *** End programmer edit section *** (IStatisticsSettings CustomAttributes)
    public interface IStatisticsSettings : NewPlatform.Flexberry.ServiceBus.Components.IServiceBusComponent
    {
        
        // *** Start programmer edit section *** (IStatisticsSettings.GetSubscriptionSB CustomAttributes)

        // *** End programmer edit section *** (IStatisticsSettings.GetSubscriptionSB CustomAttributes)
        Guid? GetSubscriptionSB();
        
        // *** Start programmer edit section *** (IStatisticsSettings.GetSettings CustomAttributes)

        // *** End programmer edit section *** (IStatisticsSettings.GetSettings CustomAttributes)
        System.Collections.Generic.IEnumerable<StatisticsSetting> GetSettings();
        
        // *** Start programmer edit section *** (IStatisticsSettings.GetSetting Subscription CustomAttributes)

        // *** End programmer edit section *** (IStatisticsSettings.GetSetting Subscription CustomAttributes)
        StatisticsSetting GetSetting(Subscription subscription);
        
        // *** Start programmer edit section *** (IStatisticsSettings.CreateSetting Subscription CustomAttributes)

        // *** End programmer edit section *** (IStatisticsSettings.CreateSetting Subscription CustomAttributes)
        StatisticsSetting CreateSetting(Subscription subscription);
    }
}
