//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ServiceBus.Components
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ISubscriptionsManager.
    /// </summary>
    // *** Start programmer edit section *** (ISubscriptionsManager CustomAttributes)

    // *** End programmer edit section *** (ISubscriptionsManager CustomAttributes)
    public interface ISubscriptionsManager : NewPlatform.Flexberry.ServiceBus.Components.IServiceBusComponent
    {
        
        // *** Start programmer edit section *** (ISubscriptionsManager CustomMembers)

        // *** End programmer edit section *** (ISubscriptionsManager CustomMembers)

        
        // *** Start programmer edit section *** (ISubscriptionsManager.CreateClient System.String System.String System.String CustomAttributes)

        // *** End programmer edit section *** (ISubscriptionsManager.CreateClient System.String System.String System.String CustomAttributes)
        void CreateClient(string clientId, string name, string address = null);
        
        // *** Start programmer edit section *** (ISubscriptionsManager.DeleteClient System.String CustomAttributes)

        // *** End programmer edit section *** (ISubscriptionsManager.DeleteClient System.String CustomAttributes)
        void DeleteClient(string clientId);
        
        // *** Start programmer edit section *** (ISubscriptionsManager.GetSubscriptions System.Boolean CustomAttributes)

        // *** End programmer edit section *** (ISubscriptionsManager.GetSubscriptions System.Boolean CustomAttributes)
        System.Collections.Generic.IEnumerable<Subscription> GetSubscriptions(bool onlyActive = true);
        
        // *** Start programmer edit section *** (ISubscriptionsManager.GetSubscriptions System.String System.Boolean CustomAttributes)

        // *** End programmer edit section *** (ISubscriptionsManager.GetSubscriptions System.String System.Boolean CustomAttributes)
        System.Collections.Generic.IEnumerable<Subscription> GetSubscriptions(string clientId, bool onlyActive = true);
        
        // *** Start programmer edit section *** (ISubscriptionsManager.GetCallbackSubscriptions System.Boolean CustomAttributes)

        // *** End programmer edit section *** (ISubscriptionsManager.GetCallbackSubscriptions System.Boolean CustomAttributes)
        System.Collections.Generic.IEnumerable<Subscription> GetCallbackSubscriptions(bool onlyActive = true);
        
        // *** Start programmer edit section *** (ISubscriptionsManager.GetSubscriptionsForMsgType System.String System.String CustomAttributes)

        // *** End programmer edit section *** (ISubscriptionsManager.GetSubscriptionsForMsgType System.String System.String CustomAttributes)
        System.Collections.Generic.IEnumerable<Subscription> GetSubscriptionsForMsgType(string messageTypeId, string senderId = null);
        
        // *** Start programmer edit section *** (ISubscriptionsManager.SubscribeOrUpdate System.String System.String System.Boolean TransportType? DateTime? CustomAttributes)

        // *** End programmer edit section *** (ISubscriptionsManager.SubscribeOrUpdate System.String System.String System.Boolean TransportType? DateTime? CustomAttributes)
        void SubscribeOrUpdate(string clientId, string messageTypeId, bool isCallback, TransportType? transportType, DateTime? expiryDate = null, string subscribtionId = null);
        
        // *** Start programmer edit section *** (ISubscriptionsManager.UpdateAllSubscriptions System.String CustomAttributes)

        // *** End programmer edit section *** (ISubscriptionsManager.UpdateAllSubscriptions System.String CustomAttributes)
        void UpdateAllSubscriptions(string clientId);
        
        // *** Start programmer edit section *** (ISubscriptionsManager.UpdateClient System.String NewPlatform.Flexberry.ServiceBus.ServiceBusClient CustomAttributes)

        // *** End programmer edit section *** (ISubscriptionsManager.UpdateClient System.String NewPlatform.Flexberry.ServiceBus.ServiceBusClient CustomAttributes)
        void UpdateClient(string clientId, NewPlatform.Flexberry.ServiceBus.ServiceBusClient client);
        
        // *** Start programmer edit section *** (ISubscriptionsManager.CreateMessageType NewPlatform.Flexberry.ServiceBus.ServiceBusMessageType CustomAttributes)

        // *** End programmer edit section *** (ISubscriptionsManager.CreateMessageType NewPlatform.Flexberry.ServiceBus.ServiceBusMessageType CustomAttributes)
        void CreateMessageType(NewPlatform.Flexberry.ServiceBus.ServiceBusMessageType msgTypeInfo);
        
        // *** Start programmer edit section *** (ISubscriptionsManager.UpdateMessageType System.String NewPlatform.Flexberry.ServiceBus.ServiceBusMessageType CustomAttributes)

        // *** End programmer edit section *** (ISubscriptionsManager.UpdateMessageType System.String NewPlatform.Flexberry.ServiceBus.ServiceBusMessageType CustomAttributes)
        void UpdateMessageType(string messageTypeId, NewPlatform.Flexberry.ServiceBus.ServiceBusMessageType messageType);
        
        // *** Start programmer edit section *** (ISubscriptionsManager.DeleteMessageType System.String CustomAttributes)

        // *** End programmer edit section *** (ISubscriptionsManager.DeleteMessageType System.String CustomAttributes)
        void DeleteMessageType(string messageTypeId);
        
        // *** Start programmer edit section *** (ISubscriptionsManager.UpdateSubscription System.String NewPlatform.Flexberry.ServiceBus.ServiceBusSubscription CustomAttributes)

        // *** End programmer edit section *** (ISubscriptionsManager.UpdateSubscription System.String NewPlatform.Flexberry.ServiceBus.ServiceBusSubscription CustomAttributes)
        void UpdateSubscription(string subscriptionId, NewPlatform.Flexberry.ServiceBus.ServiceBusSubscription subscription);
        
        // *** Start programmer edit section *** (ISubscriptionsManager.DeleteSubscription System.String CustomAttributes)

        // *** End programmer edit section *** (ISubscriptionsManager.DeleteSubscription System.String CustomAttributes)
        void DeleteSubscription(string subscriptionId);
    }
}
