//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ServiceBus.Components
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// IWebApiService.
    /// </summary>
    // *** Start programmer edit section *** (IWebApiService CustomAttributes)

    // *** End programmer edit section *** (IWebApiService CustomAttributes)
    public interface IWebApiService : NewPlatform.Flexberry.ServiceBus.Components.IServiceBusComponent
    {
        
        // *** Start programmer edit section *** (IWebApiService CustomMembers)

        // *** End programmer edit section *** (IWebApiService CustomMembers)

    }
}
