//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ServiceBus.Components
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ICacheable.
    /// </summary>
    // *** Start programmer edit section *** (ICacheable CustomAttributes)

    // *** End programmer edit section *** (ICacheable CustomAttributes)
    public interface ICacheable
    {
        
        // *** Start programmer edit section *** (ICacheable.ClearCache CustomAttributes)

        // *** End programmer edit section *** (ICacheable.ClearCache CustomAttributes)
        void ClearCache();
    }
}
