//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ServiceBus.Components
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// IStatisticsTimeService.
    /// </summary>
    // *** Start programmer edit section *** (IStatisticsTimeService CustomAttributes)

    // *** End programmer edit section *** (IStatisticsTimeService CustomAttributes)
    public interface IStatisticsTimeService : NewPlatform.Flexberry.ServiceBus.Components.IServiceBusComponent
    {
        
        /// <summary>
        /// Now.
        /// </summary>
        // *** Start programmer edit section *** (Now CustomAttributes)

        // *** End programmer edit section *** (Now CustomAttributes)
        System.DateTime Now
        {
            get;
        }
    }
}
