//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ServiceBus
{

    using System;
    using System.Xml;

    // *** Start programmer edit section *** (Using statements)
    using System.Linq;
    using ICSSoft.STORMNET.Business.LINQProvider;
    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ClientBS.
    /// </summary>
    // *** Start programmer edit section *** (ClientBS CustomAttributes)

    // *** End programmer edit section *** (ClientBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.@this)]
    public class ClientBS : ICSSoft.STORMNET.Business.BusinessServer
    {

        // *** Start programmer edit section *** (ClientBS CustomMembers)

        // *** End programmer edit section *** (ClientBS CustomMembers)


        // *** Start programmer edit section *** (OnUpdateClient CustomAttributes)

        // *** End programmer edit section *** (OnUpdateClient CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateClient(NewPlatform.Flexberry.ServiceBus.Client UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateClient)
            Client existingClient = DataService.Query<Client>(Client.Views.EditView).Where(c => c.ID == UpdatedObject.ID && c.__PrimaryKey != UpdatedObject.__PrimaryKey).FirstOrDefault();

            if (existingClient != null)
            {
                throw new Exception($"Client with ID=\"{UpdatedObject.ID}\" already exists.");
            }

            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateClient)
        }
    }
}
