//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ServiceBus
{
    using System;
    using System.Xml;


    // *** Start programmer edit section *** (Using statements)
    using System.Linq;
    using ICSSoft.STORMNET.Business.LINQProvider;
    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// MessageTypeBS.
    /// </summary>
    // *** Start programmer edit section *** (MessageTypeBS CustomAttributes)

    // *** End programmer edit section *** (MessageTypeBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.@this)]
    public class MessageTypeBS : ICSSoft.STORMNET.Business.BusinessServer
    {

        // *** Start programmer edit section *** (MessageTypeBS CustomMembers)

        // *** End programmer edit section *** (MessageTypeBS CustomMembers)


        // *** Start programmer edit section *** (OnUpdateMessageType CustomAttributes)

        // *** End programmer edit section *** (OnUpdateMessageType CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateMessageType(NewPlatform.Flexberry.ServiceBus.MessageType UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateMessageType)
            MessageType existingMessageType = DataService.Query<MessageType>(MessageType.Views.EditView).Where(m => m.ID == UpdatedObject.ID && m.__PrimaryKey != UpdatedObject.__PrimaryKey).FirstOrDefault();

            if (existingMessageType != null)
            {
                throw new Exception($"Message type with ID=\"{UpdatedObject.ID}\" already exists.");
            }

            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateMessageType)
        }
    }
}
