//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ServiceBus
{
    using System;
    using System.Xml;


    // *** Start programmer edit section *** (Using statements)
    using System.Linq;
    using ICSSoft.STORMNET.Business.LINQProvider;
    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// MessageBS.
    /// </summary>
    // *** Start programmer edit section *** (MessageBS CustomAttributes)

    // *** End programmer edit section *** (MessageBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.@this)]
    public class MessageBS : ICSSoft.STORMNET.Business.BusinessServer
    {

        // *** Start programmer edit section *** (MessageBS CustomMembers)

        // *** End programmer edit section *** (MessageBS CustomMembers)


        // *** Start programmer edit section *** (OnUpdateMessage CustomAttributes)

        // *** End programmer edit section *** (OnUpdateMessage CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateMessage(NewPlatform.Flexberry.ServiceBus.Message UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateMessage)
            if (!string.IsNullOrEmpty(UpdatedObject.Group) &&
                DataService.Query<Message>().Count(m =>
                    m.Recipient.__PrimaryKey == UpdatedObject.Recipient.__PrimaryKey &&
                    m.MessageType.__PrimaryKey == UpdatedObject.MessageType.__PrimaryKey &&
                    m.Group == UpdatedObject.Group && m.IsSending == false) > 0)
            {
                throw new Exception($"A similar message with the group '{UpdatedObject.Group}' already exists.");
            }

            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateMessage)
        }
    }
}
