ALTER TABLE Шина ALTER COLUMN description TYPE VARCHAR; ALTER TABLE Шина ALTER COLUMN description DROP NOT NULL;
ALTER TABLE Клиент ALTER COLUMN description TYPE VARCHAR; ALTER TABLE Клиент ALTER COLUMN description DROP NOT NULL;
ALTER TABLE Подписка ALTER COLUMN Описание TYPE VARCHAR; ALTER TABLE Подписка ALTER COLUMN Описание DROP NOT NULL;
ALTER TABLE ТипСообщения ALTER COLUMN Комментарий TYPE VARCHAR; ALTER TABLE ТипСообщения ALTER COLUMN Комментарий DROP NOT NULL;
