//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ServiceBus
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// HttpMessageFromEsb.
    /// </summary>
    // *** Start programmer edit section *** (HttpMessageFromEsb CustomAttributes)

    // *** End programmer edit section *** (HttpMessageFromEsb CustomAttributes)
    public class HttpMessageFromEsb
    {
        
        private string fId;
        
        private string fBody;
        
        private System.DateTime fMessageFormingTime;
        
        private string fMessageTypeID;
        
        private string fSenderName;
        
        private string fGroupID;
        
        private System.Collections.Generic.Dictionary<string, string> fTags;
        
        private byte[] fAttachment;
        
        // *** Start programmer edit section *** (HttpMessageFromEsb CustomMembers)

        // *** End programmer edit section *** (HttpMessageFromEsb CustomMembers)

        
        /// <summary>
        /// Id.
        /// </summary>
        // *** Start programmer edit section *** (HttpMessageFromEsb.Id CustomAttributes)

        // *** End programmer edit section *** (HttpMessageFromEsb.Id CustomAttributes)
        public virtual string Id
        {
            get
            {
                // *** Start programmer edit section *** (HttpMessageFromEsb.Id Get start)

                // *** End programmer edit section *** (HttpMessageFromEsb.Id Get start)
                string result = this.fId;
                // *** Start programmer edit section *** (HttpMessageFromEsb.Id Get end)

                // *** End programmer edit section *** (HttpMessageFromEsb.Id Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (HttpMessageFromEsb.Id Set start)

                // *** End programmer edit section *** (HttpMessageFromEsb.Id Set start)
                this.fId = value;
                // *** Start programmer edit section *** (HttpMessageFromEsb.Id Set end)

                // *** End programmer edit section *** (HttpMessageFromEsb.Id Set end)
            }
        }
        
        /// <summary>
        /// Body.
        /// </summary>
        // *** Start programmer edit section *** (HttpMessageFromEsb.Body CustomAttributes)

        // *** End programmer edit section *** (HttpMessageFromEsb.Body CustomAttributes)
        public virtual string Body
        {
            get
            {
                // *** Start programmer edit section *** (HttpMessageFromEsb.Body Get start)

                // *** End programmer edit section *** (HttpMessageFromEsb.Body Get start)
                string result = this.fBody;
                // *** Start programmer edit section *** (HttpMessageFromEsb.Body Get end)

                // *** End programmer edit section *** (HttpMessageFromEsb.Body Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (HttpMessageFromEsb.Body Set start)

                // *** End programmer edit section *** (HttpMessageFromEsb.Body Set start)
                this.fBody = value;
                // *** Start programmer edit section *** (HttpMessageFromEsb.Body Set end)

                // *** End programmer edit section *** (HttpMessageFromEsb.Body Set end)
            }
        }
        
        /// <summary>
        /// MessageFormingTime.
        /// </summary>
        // *** Start programmer edit section *** (HttpMessageFromEsb.MessageFormingTime CustomAttributes)

        // *** End programmer edit section *** (HttpMessageFromEsb.MessageFormingTime CustomAttributes)
        public virtual System.DateTime MessageFormingTime
        {
            get
            {
                // *** Start programmer edit section *** (HttpMessageFromEsb.MessageFormingTime Get start)

                // *** End programmer edit section *** (HttpMessageFromEsb.MessageFormingTime Get start)
                System.DateTime result = this.fMessageFormingTime;
                // *** Start programmer edit section *** (HttpMessageFromEsb.MessageFormingTime Get end)

                // *** End programmer edit section *** (HttpMessageFromEsb.MessageFormingTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (HttpMessageFromEsb.MessageFormingTime Set start)

                // *** End programmer edit section *** (HttpMessageFromEsb.MessageFormingTime Set start)
                this.fMessageFormingTime = value;
                // *** Start programmer edit section *** (HttpMessageFromEsb.MessageFormingTime Set end)

                // *** End programmer edit section *** (HttpMessageFromEsb.MessageFormingTime Set end)
            }
        }
        
        /// <summary>
        /// MessageTypeID.
        /// </summary>
        // *** Start programmer edit section *** (HttpMessageFromEsb.MessageTypeID CustomAttributes)

        // *** End programmer edit section *** (HttpMessageFromEsb.MessageTypeID CustomAttributes)
        public virtual string MessageTypeID
        {
            get
            {
                // *** Start programmer edit section *** (HttpMessageFromEsb.MessageTypeID Get start)

                // *** End programmer edit section *** (HttpMessageFromEsb.MessageTypeID Get start)
                string result = this.fMessageTypeID;
                // *** Start programmer edit section *** (HttpMessageFromEsb.MessageTypeID Get end)

                // *** End programmer edit section *** (HttpMessageFromEsb.MessageTypeID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (HttpMessageFromEsb.MessageTypeID Set start)

                // *** End programmer edit section *** (HttpMessageFromEsb.MessageTypeID Set start)
                this.fMessageTypeID = value;
                // *** Start programmer edit section *** (HttpMessageFromEsb.MessageTypeID Set end)

                // *** End programmer edit section *** (HttpMessageFromEsb.MessageTypeID Set end)
            }
        }
        
        /// <summary>
        /// SenderName.
        /// </summary>
        // *** Start programmer edit section *** (HttpMessageFromEsb.SenderName CustomAttributes)

        // *** End programmer edit section *** (HttpMessageFromEsb.SenderName CustomAttributes)
        public virtual string SenderName
        {
            get
            {
                // *** Start programmer edit section *** (HttpMessageFromEsb.SenderName Get start)

                // *** End programmer edit section *** (HttpMessageFromEsb.SenderName Get start)
                string result = this.fSenderName;
                // *** Start programmer edit section *** (HttpMessageFromEsb.SenderName Get end)

                // *** End programmer edit section *** (HttpMessageFromEsb.SenderName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (HttpMessageFromEsb.SenderName Set start)

                // *** End programmer edit section *** (HttpMessageFromEsb.SenderName Set start)
                this.fSenderName = value;
                // *** Start programmer edit section *** (HttpMessageFromEsb.SenderName Set end)

                // *** End programmer edit section *** (HttpMessageFromEsb.SenderName Set end)
            }
        }
        
        /// <summary>
        /// GroupID.
        /// </summary>
        // *** Start programmer edit section *** (HttpMessageFromEsb.GroupID CustomAttributes)

        // *** End programmer edit section *** (HttpMessageFromEsb.GroupID CustomAttributes)
        public virtual string GroupID
        {
            get
            {
                // *** Start programmer edit section *** (HttpMessageFromEsb.GroupID Get start)

                // *** End programmer edit section *** (HttpMessageFromEsb.GroupID Get start)
                string result = this.fGroupID;
                // *** Start programmer edit section *** (HttpMessageFromEsb.GroupID Get end)

                // *** End programmer edit section *** (HttpMessageFromEsb.GroupID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (HttpMessageFromEsb.GroupID Set start)

                // *** End programmer edit section *** (HttpMessageFromEsb.GroupID Set start)
                this.fGroupID = value;
                // *** Start programmer edit section *** (HttpMessageFromEsb.GroupID Set end)

                // *** End programmer edit section *** (HttpMessageFromEsb.GroupID Set end)
            }
        }
        
        /// <summary>
        /// Tags.
        /// </summary>
        // *** Start programmer edit section *** (HttpMessageFromEsb.Tags CustomAttributes)

        // *** End programmer edit section *** (HttpMessageFromEsb.Tags CustomAttributes)
        public virtual System.Collections.Generic.Dictionary<string, string> Tags
        {
            get
            {
                // *** Start programmer edit section *** (HttpMessageFromEsb.Tags Get start)

                // *** End programmer edit section *** (HttpMessageFromEsb.Tags Get start)
                System.Collections.Generic.Dictionary<string, string> result = this.fTags;
                // *** Start programmer edit section *** (HttpMessageFromEsb.Tags Get end)

                // *** End programmer edit section *** (HttpMessageFromEsb.Tags Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (HttpMessageFromEsb.Tags Set start)

                // *** End programmer edit section *** (HttpMessageFromEsb.Tags Set start)
                this.fTags = value;
                // *** Start programmer edit section *** (HttpMessageFromEsb.Tags Set end)

                // *** End programmer edit section *** (HttpMessageFromEsb.Tags Set end)
            }
        }
        
        /// <summary>
        /// Attachment.
        /// </summary>
        // *** Start programmer edit section *** (HttpMessageFromEsb.Attachment CustomAttributes)

        // *** End programmer edit section *** (HttpMessageFromEsb.Attachment CustomAttributes)
        public virtual byte[] Attachment
        {
            get
            {
                // *** Start programmer edit section *** (HttpMessageFromEsb.Attachment Get start)

                // *** End programmer edit section *** (HttpMessageFromEsb.Attachment Get start)
                byte[] result = this.fAttachment;
                // *** Start programmer edit section *** (HttpMessageFromEsb.Attachment Get end)

                // *** End programmer edit section *** (HttpMessageFromEsb.Attachment Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (HttpMessageFromEsb.Attachment Set start)

                // *** End programmer edit section *** (HttpMessageFromEsb.Attachment Set start)
                this.fAttachment = value;
                // *** Start programmer edit section *** (HttpMessageFromEsb.Attachment Set end)

                // *** End programmer edit section *** (HttpMessageFromEsb.Attachment Set end)
            }
        }
    }
}
