//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ServiceBus
{
    using System;
    using System.Xml;


    // *** Start programmer edit section *** (Using statements)
    using System.ServiceModel;
    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// IServiceBusClient.
    /// </summary>
    // *** Start programmer edit section *** (IServiceBusClient CustomAttributes)
    [ServiceContract(Namespace = "http://tempuri.org/", ConfigurationName = "FlexberryServiceBus.IServiceBusClient")]
    // *** End programmer edit section *** (IServiceBusClient CustomAttributes)
    public interface IServiceBusClient
    {

        // *** Start programmer edit section *** (IServiceBusClient CustomMembers)

        // *** End programmer edit section *** (IServiceBusClient CustomMembers)


        // *** Start programmer edit section *** (IServiceBusClient.GetMessageInfo System.String System.String CustomAttributes)
        [OperationContract(Name = "GetMessageInfo")]
        // *** End programmer edit section *** (IServiceBusClient.GetMessageInfo System.String System.String CustomAttributes)
        NewPlatform.Flexberry.ServiceBus.ServiceBusMessageInfo GetMessageInfo(string clientId, string messageTypeId);

        // *** Start programmer edit section *** (IServiceBusClient.SendMessage NewPlatform.Flexberry.ServiceBus.ServiceBusMessage CustomAttributes)
        [OperationContract(Name = "SendMessage")]
        // *** End programmer edit section *** (IServiceBusClient.SendMessage NewPlatform.Flexberry.ServiceBus.ServiceBusMessage CustomAttributes)
        void SendMessage(NewPlatform.Flexberry.ServiceBus.ServiceBusMessage message);

        // *** Start programmer edit section *** (IServiceBusClient.SendMessage NewPlatform.Flexberry.ServiceBus.ServiceBusMessage System.String CustomAttributes)
        [OperationContract(Name = "SendMessageWithGroup")]
        // *** End programmer edit section *** (IServiceBusClient.SendMessage NewPlatform.Flexberry.ServiceBus.ServiceBusMessage System.String CustomAttributes)
        void SendMessage(NewPlatform.Flexberry.ServiceBus.ServiceBusMessage message, string group);

        // *** Start programmer edit section *** (IServiceBusClient.GetMessage System.String System.String CustomAttributes)
        [OperationContract(Name = "GetMessage")]
        // *** End programmer edit section *** (IServiceBusClient.GetMessage System.String System.String CustomAttributes)
        NewPlatform.Flexberry.ServiceBus.ServiceBusMessage GetMessage(string clientId, string messageTypeId);

        // *** Start programmer edit section *** (IServiceBusClient.GetMessage System.String System.String System.String CustomAttributes)
        [OperationContract(Name = "GetMessageWithGroup")]
        // *** End programmer edit section *** (IServiceBusClient.GetMessage System.String System.String System.String CustomAttributes)
        NewPlatform.Flexberry.ServiceBus.ServiceBusMessage GetMessage(string clientId, string messageTypeId, string group);

        // *** Start programmer edit section *** (IServiceBusClient.GetMessage System.String System.String string[] CustomAttributes)
        [OperationContract(Name = "GetMessageWithTags")]
        // *** End programmer edit section *** (IServiceBusClient.GetMessage System.String System.String string[] CustomAttributes)
        NewPlatform.Flexberry.ServiceBus.ServiceBusMessage GetMessage(string clientId, string messageTypeId, string[] tags);

        // *** Start programmer edit section *** (IServiceBusClient.GetMessageInfo System.String System.String System.String CustomAttributes)
        [OperationContract(Name = "GetMessageInfoWithGroup")]
        // *** End programmer edit section *** (IServiceBusClient.GetMessageInfo System.String System.String System.String CustomAttributes)
        NewPlatform.Flexberry.ServiceBus.ServiceBusMessageInfo GetMessageInfo(string clientId, string messageTypeId, string group);

        // *** Start programmer edit section *** (IServiceBusClient.GetMessageInfo System.String System.String string[] CustomAttributes)
        [OperationContract(Name = "GetMessageInfoWithTags")]
        // *** End programmer edit section *** (IServiceBusClient.GetMessageInfo System.String System.String string[] CustomAttributes)
        NewPlatform.Flexberry.ServiceBus.ServiceBusMessageInfo GetMessageInfo(string clientId, string messageTypeId, string[] tags);

        // *** Start programmer edit section *** (IServiceBusClient.GetCurrentMessageCount System.String System.String CustomAttributes)
        [OperationContract(Name = "GetCurrentMessageCountByMessageType")]
        // *** End programmer edit section *** (IServiceBusClient.GetCurrentMessageCount System.String System.String CustomAttributes)
        int GetCurrentMessageCount(string clientId, string messageTypeId);

        // *** Start programmer edit section *** (IServiceBusClient.GetCurrentMessageCount System.String CustomAttributes)
        [OperationContract(Name = "GetCurrentMessageCount")]
        // *** End programmer edit section *** (IServiceBusClient.GetCurrentMessageCount System.String CustomAttributes)
        int GetCurrentMessageCount(string clientId);
    }
}
