//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ServiceBus.Components
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// IServiceBusComponent.
    /// </summary>
    // *** Start programmer edit section *** (IServiceBusComponent CustomAttributes)

    // *** End programmer edit section *** (IServiceBusComponent CustomAttributes)
    public interface IServiceBusComponent
    {
        
        // *** Start programmer edit section *** (IServiceBusComponent CustomMembers)

        // *** End programmer edit section *** (IServiceBusComponent CustomMembers)

        
        // *** Start programmer edit section *** (IServiceBusComponent.Prepare CustomAttributes)

        // *** End programmer edit section *** (IServiceBusComponent.Prepare CustomAttributes)
        void Prepare();
        
        // *** Start programmer edit section *** (IServiceBusComponent.Start CustomAttributes)

        // *** End programmer edit section *** (IServiceBusComponent.Start CustomAttributes)
        void Start();
        
        // *** Start programmer edit section *** (IServiceBusComponent.Stop CustomAttributes)

        // *** End programmer edit section *** (IServiceBusComponent.Stop CustomAttributes)
        void Stop();
        
        // *** Start programmer edit section *** (IServiceBusComponent.AfterStop CustomAttributes)

        // *** End programmer edit section *** (IServiceBusComponent.AfterStop CustomAttributes)
        void AfterStop();
    }
}
