//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ServiceBus
{
    using System;
    using System.Xml;


    // *** Start programmer edit section *** (Using statements)
    using System.ServiceModel;
    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// IServiceBusCallbackSubscriber.
    /// </summary>
    // *** Start programmer edit section *** (IServiceBusCallbackSubscriber CustomAttributes)
    [ServiceContract(Namespace = "http://tempuri.org/", ConfigurationName = "FlexberryServiceBus.IServiceBusCallbackSubscriber")]
    // *** End programmer edit section *** (IServiceBusCallbackSubscriber CustomAttributes)
    public interface IServiceBusCallbackSubscriber
    {

        // *** Start programmer edit section *** (IServiceBusCallbackSubscriber CustomMembers)

        // *** End programmer edit section *** (IServiceBusCallbackSubscriber CustomMembers)


        // *** Start programmer edit section *** (IServiceBusCallbackSubscriber.AcceptMessage NewPlatform.Flexberry.ServiceBus.ServiceBusMessage CustomAttributes)
        [OperationContract]
        // *** End programmer edit section *** (IServiceBusCallbackSubscriber.AcceptMessage NewPlatform.Flexberry.ServiceBus.ServiceBusMessage CustomAttributes)
        void AcceptMessage(NewPlatform.Flexberry.ServiceBus.ServiceBusMessage message);

        // *** Start programmer edit section *** (IServiceBusCallbackSubscriber.GetSourceId CustomAttributes)
        [OperationContract]
        // *** End programmer edit section *** (IServiceBusCallbackSubscriber.GetSourceId CustomAttributes)
        string GetSourceId();
    }
}
