//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ServiceBus
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)
    using System.Runtime.Serialization;
    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// MessageOrderingInformation.
    /// </summary>
    // *** Start programmer edit section *** (MessageOrderingInformation CustomAttributes)
    [DataContract(Namespace = "http://schemas.datacontract.org/2004/07/IIS.Persona.ServiceBus.Objects")]
    [Obsolete("This type is not used instead of it use ServiceBusMessageInfo")]
    // *** End programmer edit section *** (MessageOrderingInformation CustomAttributes)
    public class MessageOrderingInformation
    {
        
        private int fPriority = 0;
        
        private System.DateTime fFormingTime;
        
        // *** Start programmer edit section *** (MessageOrderingInformation CustomMembers)

        // *** End programmer edit section *** (MessageOrderingInformation CustomMembers)

        
        /// <summary>
        /// Priority.
        /// </summary>
        // *** Start programmer edit section *** (MessageOrderingInformation.Priority CustomAttributes)
        [DataMember]
        // *** End programmer edit section *** (MessageOrderingInformation.Priority CustomAttributes)
        public virtual int Priority
        {
            get
            {
                // *** Start programmer edit section *** (MessageOrderingInformation.Priority Get start)

                // *** End programmer edit section *** (MessageOrderingInformation.Priority Get start)
                int result = this.fPriority;
                // *** Start programmer edit section *** (MessageOrderingInformation.Priority Get end)

                // *** End programmer edit section *** (MessageOrderingInformation.Priority Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MessageOrderingInformation.Priority Set start)

                // *** End programmer edit section *** (MessageOrderingInformation.Priority Set start)
                this.fPriority = value;
                // *** Start programmer edit section *** (MessageOrderingInformation.Priority Set end)

                // *** End programmer edit section *** (MessageOrderingInformation.Priority Set end)
            }
        }
        
        /// <summary>
        /// FormingTime.
        /// </summary>
        // *** Start programmer edit section *** (MessageOrderingInformation.FormingTime CustomAttributes)
        [DataMember]
        // *** End programmer edit section *** (MessageOrderingInformation.FormingTime CustomAttributes)
        public virtual System.DateTime FormingTime
        {
            get
            {
                // *** Start programmer edit section *** (MessageOrderingInformation.FormingTime Get start)

                // *** End programmer edit section *** (MessageOrderingInformation.FormingTime Get start)
                System.DateTime result = this.fFormingTime;
                // *** Start programmer edit section *** (MessageOrderingInformation.FormingTime Get end)

                // *** End programmer edit section *** (MessageOrderingInformation.FormingTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MessageOrderingInformation.FormingTime Set start)

                // *** End programmer edit section *** (MessageOrderingInformation.FormingTime Set start)
                this.fFormingTime = value;
                // *** Start programmer edit section *** (MessageOrderingInformation.FormingTime Set end)

                // *** End programmer edit section *** (MessageOrderingInformation.FormingTime Set end)
            }
        }
    }
}
