//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ServiceBus
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)
    using System.Runtime.Serialization;
    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// MessageFromESB.
    /// </summary>
    // *** Start programmer edit section *** (MessageFromESB CustomAttributes)
    [DataContract(Namespace = "http://schemas.datacontract.org/2004/07/IIS.Persona.ServiceBus.Objects")]
    // *** End programmer edit section *** (MessageFromESB CustomAttributes)
    public class MessageFromESB
    {
        
        private string fBody;
        
        private System.DateTime fMessageFormingTime;
        
        private string fMessageTypeID;
        
        private string fSenderName;
        
        private string fGroupID;
        
        private System.Collections.Generic.Dictionary<string, string> fTags;
        
        private byte[] fAttachment;
        
        // *** Start programmer edit section *** (MessageFromESB CustomMembers)

        // *** End programmer edit section *** (MessageFromESB CustomMembers)

        
        /// <summary>
        /// Body.
        /// </summary>
        // *** Start programmer edit section *** (MessageFromESB.Body CustomAttributes)
        [DataMember]
        // *** End programmer edit section *** (MessageFromESB.Body CustomAttributes)
        public virtual string Body
        {
            get
            {
                // *** Start programmer edit section *** (MessageFromESB.Body Get start)

                // *** End programmer edit section *** (MessageFromESB.Body Get start)
                string result = this.fBody;
                // *** Start programmer edit section *** (MessageFromESB.Body Get end)

                // *** End programmer edit section *** (MessageFromESB.Body Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MessageFromESB.Body Set start)

                // *** End programmer edit section *** (MessageFromESB.Body Set start)
                this.fBody = value;
                // *** Start programmer edit section *** (MessageFromESB.Body Set end)

                // *** End programmer edit section *** (MessageFromESB.Body Set end)
            }
        }
        
        /// <summary>
        /// MessageFormingTime.
        /// </summary>
        // *** Start programmer edit section *** (MessageFromESB.MessageFormingTime CustomAttributes)
        [DataMember]
        // *** End programmer edit section *** (MessageFromESB.MessageFormingTime CustomAttributes)
        public virtual System.DateTime MessageFormingTime
        {
            get
            {
                // *** Start programmer edit section *** (MessageFromESB.MessageFormingTime Get start)

                // *** End programmer edit section *** (MessageFromESB.MessageFormingTime Get start)
                System.DateTime result = this.fMessageFormingTime;
                // *** Start programmer edit section *** (MessageFromESB.MessageFormingTime Get end)

                // *** End programmer edit section *** (MessageFromESB.MessageFormingTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MessageFromESB.MessageFormingTime Set start)

                // *** End programmer edit section *** (MessageFromESB.MessageFormingTime Set start)
                this.fMessageFormingTime = value;
                // *** Start programmer edit section *** (MessageFromESB.MessageFormingTime Set end)

                // *** End programmer edit section *** (MessageFromESB.MessageFormingTime Set end)
            }
        }
        
        /// <summary>
        /// MessageTypeID.
        /// </summary>
        // *** Start programmer edit section *** (MessageFromESB.MessageTypeID CustomAttributes)
        [DataMember]
        // *** End programmer edit section *** (MessageFromESB.MessageTypeID CustomAttributes)
        public virtual string MessageTypeID
        {
            get
            {
                // *** Start programmer edit section *** (MessageFromESB.MessageTypeID Get start)

                // *** End programmer edit section *** (MessageFromESB.MessageTypeID Get start)
                string result = this.fMessageTypeID;
                // *** Start programmer edit section *** (MessageFromESB.MessageTypeID Get end)

                // *** End programmer edit section *** (MessageFromESB.MessageTypeID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MessageFromESB.MessageTypeID Set start)

                // *** End programmer edit section *** (MessageFromESB.MessageTypeID Set start)
                this.fMessageTypeID = value;
                // *** Start programmer edit section *** (MessageFromESB.MessageTypeID Set end)

                // *** End programmer edit section *** (MessageFromESB.MessageTypeID Set end)
            }
        }
        
        /// <summary>
        /// SenderName.
        /// </summary>
        // *** Start programmer edit section *** (MessageFromESB.SenderName CustomAttributes)
        [DataMember]
        // *** End programmer edit section *** (MessageFromESB.SenderName CustomAttributes)
        public virtual string SenderName
        {
            get
            {
                // *** Start programmer edit section *** (MessageFromESB.SenderName Get start)

                // *** End programmer edit section *** (MessageFromESB.SenderName Get start)
                string result = this.fSenderName;
                // *** Start programmer edit section *** (MessageFromESB.SenderName Get end)

                // *** End programmer edit section *** (MessageFromESB.SenderName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MessageFromESB.SenderName Set start)

                // *** End programmer edit section *** (MessageFromESB.SenderName Set start)
                this.fSenderName = value;
                // *** Start programmer edit section *** (MessageFromESB.SenderName Set end)

                // *** End programmer edit section *** (MessageFromESB.SenderName Set end)
            }
        }
        
        /// <summary>
        /// GroupID.
        /// </summary>
        // *** Start programmer edit section *** (MessageFromESB.GroupID CustomAttributes)
        [DataMember]
        // *** End programmer edit section *** (MessageFromESB.GroupID CustomAttributes)
        public virtual string GroupID
        {
            get
            {
                // *** Start programmer edit section *** (MessageFromESB.GroupID Get start)

                // *** End programmer edit section *** (MessageFromESB.GroupID Get start)
                string result = this.fGroupID;
                // *** Start programmer edit section *** (MessageFromESB.GroupID Get end)

                // *** End programmer edit section *** (MessageFromESB.GroupID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MessageFromESB.GroupID Set start)

                // *** End programmer edit section *** (MessageFromESB.GroupID Set start)
                this.fGroupID = value;
                // *** Start programmer edit section *** (MessageFromESB.GroupID Set end)

                // *** End programmer edit section *** (MessageFromESB.GroupID Set end)
            }
        }
        
        /// <summary>
        /// Tags.
        /// </summary>
        // *** Start programmer edit section *** (MessageFromESB.Tags CustomAttributes)
        [DataMember]
        // *** End programmer edit section *** (MessageFromESB.Tags CustomAttributes)
        public virtual System.Collections.Generic.Dictionary<string, string> Tags
        {
            get
            {
                // *** Start programmer edit section *** (MessageFromESB.Tags Get start)

                // *** End programmer edit section *** (MessageFromESB.Tags Get start)
                System.Collections.Generic.Dictionary<string, string> result = this.fTags;
                // *** Start programmer edit section *** (MessageFromESB.Tags Get end)

                // *** End programmer edit section *** (MessageFromESB.Tags Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MessageFromESB.Tags Set start)

                // *** End programmer edit section *** (MessageFromESB.Tags Set start)
                this.fTags = value;
                // *** Start programmer edit section *** (MessageFromESB.Tags Set end)

                // *** End programmer edit section *** (MessageFromESB.Tags Set end)
            }
        }
        
        /// <summary>
        /// Attachment.
        /// </summary>
        // *** Start programmer edit section *** (MessageFromESB.Attachment CustomAttributes)
        [DataMember]
        // *** End programmer edit section *** (MessageFromESB.Attachment CustomAttributes)
        public virtual byte[] Attachment
        {
            get
            {
                // *** Start programmer edit section *** (MessageFromESB.Attachment Get start)

                // *** End programmer edit section *** (MessageFromESB.Attachment Get start)
                byte[] result = this.fAttachment;
                // *** Start programmer edit section *** (MessageFromESB.Attachment Get end)

                // *** End programmer edit section *** (MessageFromESB.Attachment Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MessageFromESB.Attachment Set start)

                // *** End programmer edit section *** (MessageFromESB.Attachment Set start)
                this.fAttachment = value;
                // *** Start programmer edit section *** (MessageFromESB.Attachment Set end)

                // *** End programmer edit section *** (MessageFromESB.Attachment Set end)
            }
        }
    }
}
