//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ServiceBus
{
    using System;
    using System.Xml;


    // *** Start programmer edit section *** (Using statements)
    using System.Runtime.Serialization;
    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ServiceBusMessageInfo.
    /// </summary>
    // *** Start programmer edit section *** (ServiceBusMessageInfo CustomAttributes)
    [DataContract(Namespace = "http://schemas.datacontract.org/2004/07/IIS.Persona.ServiceBus.Objects")]
    // *** End programmer edit section *** (ServiceBusMessageInfo CustomAttributes)
    public class ServiceBusMessageInfo
    {
        
        private string fID;
        
        private string fMessageTypeID;
        
        private int fPriority = 0;
        
        private System.DateTime fFormingTime;

        // *** Start programmer edit section *** (ServiceBusMessageInfo CustomMembers)

        // *** End programmer edit section *** (ServiceBusMessageInfo CustomMembers)


        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (ServiceBusMessageInfo.ID CustomAttributes)
        [DataMember]
        // *** End programmer edit section *** (ServiceBusMessageInfo.ID CustomAttributes)
        public virtual string ID
        {
            get
            {
                // *** Start programmer edit section *** (ServiceBusMessageInfo.ID Get start)

                // *** End programmer edit section *** (ServiceBusMessageInfo.ID Get start)
                string result = this.fID;
                // *** Start programmer edit section *** (ServiceBusMessageInfo.ID Get end)

                // *** End programmer edit section *** (ServiceBusMessageInfo.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ServiceBusMessageInfo.ID Set start)

                // *** End programmer edit section *** (ServiceBusMessageInfo.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (ServiceBusMessageInfo.ID Set end)

                // *** End programmer edit section *** (ServiceBusMessageInfo.ID Set end)
            }
        }

        /// <summary>
        /// MessageTypeID.
        /// </summary>
        // *** Start programmer edit section *** (ServiceBusMessageInfo.MessageTypeID CustomAttributes)
        [DataMember]
        // *** End programmer edit section *** (ServiceBusMessageInfo.MessageTypeID CustomAttributes)
        public virtual string MessageTypeID
        {
            get
            {
                // *** Start programmer edit section *** (ServiceBusMessageInfo.MessageTypeID Get start)

                // *** End programmer edit section *** (ServiceBusMessageInfo.MessageTypeID Get start)
                string result = this.fMessageTypeID;
                // *** Start programmer edit section *** (ServiceBusMessageInfo.MessageTypeID Get end)

                // *** End programmer edit section *** (ServiceBusMessageInfo.MessageTypeID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ServiceBusMessageInfo.MessageTypeID Set start)

                // *** End programmer edit section *** (ServiceBusMessageInfo.MessageTypeID Set start)
                this.fMessageTypeID = value;
                // *** Start programmer edit section *** (ServiceBusMessageInfo.MessageTypeID Set end)

                // *** End programmer edit section *** (ServiceBusMessageInfo.MessageTypeID Set end)
            }
        }

        /// <summary>
        /// Priority.
        /// </summary>
        // *** Start programmer edit section *** (ServiceBusMessageInfo.Priority CustomAttributes)
        [DataMember]
        // *** End programmer edit section *** (ServiceBusMessageInfo.Priority CustomAttributes)
        public virtual int Priority
        {
            get
            {
                // *** Start programmer edit section *** (ServiceBusMessageInfo.Priority Get start)

                // *** End programmer edit section *** (ServiceBusMessageInfo.Priority Get start)
                int result = this.fPriority;
                // *** Start programmer edit section *** (ServiceBusMessageInfo.Priority Get end)

                // *** End programmer edit section *** (ServiceBusMessageInfo.Priority Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ServiceBusMessageInfo.Priority Set start)

                // *** End programmer edit section *** (ServiceBusMessageInfo.Priority Set start)
                this.fPriority = value;
                // *** Start programmer edit section *** (ServiceBusMessageInfo.Priority Set end)

                // *** End programmer edit section *** (ServiceBusMessageInfo.Priority Set end)
            }
        }

        /// <summary>
        /// FormingTime.
        /// </summary>
        // *** Start programmer edit section *** (ServiceBusMessageInfo.FormingTime CustomAttributes)
        [DataMember]
        // *** End programmer edit section *** (ServiceBusMessageInfo.FormingTime CustomAttributes)
        public virtual System.DateTime FormingTime
        {
            get
            {
                // *** Start programmer edit section *** (ServiceBusMessageInfo.FormingTime Get start)

                // *** End programmer edit section *** (ServiceBusMessageInfo.FormingTime Get start)
                System.DateTime result = this.fFormingTime;
                // *** Start programmer edit section *** (ServiceBusMessageInfo.FormingTime Get end)

                // *** End programmer edit section *** (ServiceBusMessageInfo.FormingTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ServiceBusMessageInfo.FormingTime Set start)

                // *** End programmer edit section *** (ServiceBusMessageInfo.FormingTime Set start)
                this.fFormingTime = value;
                // *** Start programmer edit section *** (ServiceBusMessageInfo.FormingTime Set end)

                // *** End programmer edit section *** (ServiceBusMessageInfo.FormingTime Set end)
            }
        }
    }
}
