//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ServiceBus
{
    using System;
    using System.Xml;


    // *** Start programmer edit section *** (Using statements)
    using System.Runtime.Serialization;
    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ServiceBusMessageType.
    /// </summary>
    // *** Start programmer edit section *** (ServiceBusMessageType CustomAttributes)
    [DataContract(Namespace = "http://schemas.datacontract.org/2004/07/IIS.Persona.ServiceBus.Objects")]
    // *** End programmer edit section *** (ServiceBusMessageType CustomAttributes)
    public class ServiceBusMessageType
    {
        
        private string fId;
        
        private string fName;
        
        private string fDescription;

        // *** Start programmer edit section *** (ServiceBusMessageType CustomMembers)

        // *** End programmer edit section *** (ServiceBusMessageType CustomMembers)


        /// <summary>
        /// Id.
        /// </summary>
        // *** Start programmer edit section *** (ServiceBusMessageType.Id CustomAttributes)
        [DataMember]
        // *** End programmer edit section *** (ServiceBusMessageType.Id CustomAttributes)
        public virtual string Id
        {
            get
            {
                // *** Start programmer edit section *** (ServiceBusMessageType.Id Get start)

                // *** End programmer edit section *** (ServiceBusMessageType.Id Get start)
                string result = this.fId;
                // *** Start programmer edit section *** (ServiceBusMessageType.Id Get end)

                // *** End programmer edit section *** (ServiceBusMessageType.Id Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ServiceBusMessageType.Id Set start)

                // *** End programmer edit section *** (ServiceBusMessageType.Id Set start)
                this.fId = value;
                // *** Start programmer edit section *** (ServiceBusMessageType.Id Set end)

                // *** End programmer edit section *** (ServiceBusMessageType.Id Set end)
            }
        }

        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (ServiceBusMessageType.Name CustomAttributes)
        [DataMember]
        // *** End programmer edit section *** (ServiceBusMessageType.Name CustomAttributes)
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (ServiceBusMessageType.Name Get start)

                // *** End programmer edit section *** (ServiceBusMessageType.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (ServiceBusMessageType.Name Get end)

                // *** End programmer edit section *** (ServiceBusMessageType.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ServiceBusMessageType.Name Set start)

                // *** End programmer edit section *** (ServiceBusMessageType.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (ServiceBusMessageType.Name Set end)

                // *** End programmer edit section *** (ServiceBusMessageType.Name Set end)
            }
        }

        /// <summary>
        /// Description.
        /// </summary>
        // *** Start programmer edit section *** (ServiceBusMessageType.Description CustomAttributes)
        [DataMember]
        // *** End programmer edit section *** (ServiceBusMessageType.Description CustomAttributes)
        public virtual string Description
        {
            get
            {
                // *** Start programmer edit section *** (ServiceBusMessageType.Description Get start)

                // *** End programmer edit section *** (ServiceBusMessageType.Description Get start)
                string result = this.fDescription;
                // *** Start programmer edit section *** (ServiceBusMessageType.Description Get end)

                // *** End programmer edit section *** (ServiceBusMessageType.Description Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ServiceBusMessageType.Description Set start)

                // *** End programmer edit section *** (ServiceBusMessageType.Description Set start)
                this.fDescription = value;
                // *** Start programmer edit section *** (ServiceBusMessageType.Description Set end)

                // *** End programmer edit section *** (ServiceBusMessageType.Description Set end)
            }
        }
    }
}
