//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ServiceBus
{
    using System;
    using System.Xml;


    // *** Start programmer edit section *** (Using statements)
    using System.Runtime.Serialization;
    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ServiceBusClient.
    /// </summary>
    // *** Start programmer edit section *** (ServiceBusClient CustomAttributes)
    [DataContract(Namespace = "http://schemas.datacontract.org/2004/07/IIS.Persona.ServiceBus.Objects")]
    // *** End programmer edit section *** (ServiceBusClient CustomAttributes)
    public class ServiceBusClient
    {
        
        private string fID;
        
        private string fName;
        
        private string fAddress;
        
        private string fDescription;
        
        private string fDnsIdentity;
        
        private int? fConnectionsLimit;
        
        private bool? fSequentialSent = false;

        // *** Start programmer edit section *** (ServiceBusClient CustomMembers)

        // *** End programmer edit section *** (ServiceBusClient CustomMembers)


        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (ServiceBusClient.ID CustomAttributes)
        [DataMember]
        // *** End programmer edit section *** (ServiceBusClient.ID CustomAttributes)
        public virtual string ID
        {
            get
            {
                // *** Start programmer edit section *** (ServiceBusClient.ID Get start)

                // *** End programmer edit section *** (ServiceBusClient.ID Get start)
                string result = this.fID;
                // *** Start programmer edit section *** (ServiceBusClient.ID Get end)

                // *** End programmer edit section *** (ServiceBusClient.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ServiceBusClient.ID Set start)

                // *** End programmer edit section *** (ServiceBusClient.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (ServiceBusClient.ID Set end)

                // *** End programmer edit section *** (ServiceBusClient.ID Set end)
            }
        }

        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (ServiceBusClient.Name CustomAttributes)
        [DataMember]
        // *** End programmer edit section *** (ServiceBusClient.Name CustomAttributes)
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (ServiceBusClient.Name Get start)

                // *** End programmer edit section *** (ServiceBusClient.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (ServiceBusClient.Name Get end)

                // *** End programmer edit section *** (ServiceBusClient.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ServiceBusClient.Name Set start)

                // *** End programmer edit section *** (ServiceBusClient.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (ServiceBusClient.Name Set end)

                // *** End programmer edit section *** (ServiceBusClient.Name Set end)
            }
        }

        /// <summary>
        /// Address.
        /// </summary>
        // *** Start programmer edit section *** (ServiceBusClient.Address CustomAttributes)
        [DataMember]
        // *** End programmer edit section *** (ServiceBusClient.Address CustomAttributes)
        public virtual string Address
        {
            get
            {
                // *** Start programmer edit section *** (ServiceBusClient.Address Get start)

                // *** End programmer edit section *** (ServiceBusClient.Address Get start)
                string result = this.fAddress;
                // *** Start programmer edit section *** (ServiceBusClient.Address Get end)

                // *** End programmer edit section *** (ServiceBusClient.Address Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ServiceBusClient.Address Set start)

                // *** End programmer edit section *** (ServiceBusClient.Address Set start)
                this.fAddress = value;
                // *** Start programmer edit section *** (ServiceBusClient.Address Set end)

                // *** End programmer edit section *** (ServiceBusClient.Address Set end)
            }
        }

        /// <summary>
        /// Description.
        /// </summary>
        // *** Start programmer edit section *** (ServiceBusClient.Description CustomAttributes)
        [DataMember]
        // *** End programmer edit section *** (ServiceBusClient.Description CustomAttributes)
        public virtual string Description
        {
            get
            {
                // *** Start programmer edit section *** (ServiceBusClient.Description Get start)

                // *** End programmer edit section *** (ServiceBusClient.Description Get start)
                string result = this.fDescription;
                // *** Start programmer edit section *** (ServiceBusClient.Description Get end)

                // *** End programmer edit section *** (ServiceBusClient.Description Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ServiceBusClient.Description Set start)

                // *** End programmer edit section *** (ServiceBusClient.Description Set start)
                this.fDescription = value;
                // *** Start programmer edit section *** (ServiceBusClient.Description Set end)

                // *** End programmer edit section *** (ServiceBusClient.Description Set end)
            }
        }

        /// <summary>
        /// DnsIdentity.
        /// </summary>
        // *** Start programmer edit section *** (ServiceBusClient.DnsIdentity CustomAttributes)
        [DataMember]
        // *** End programmer edit section *** (ServiceBusClient.DnsIdentity CustomAttributes)
        public virtual string DnsIdentity
        {
            get
            {
                // *** Start programmer edit section *** (ServiceBusClient.DnsIdentity Get start)

                // *** End programmer edit section *** (ServiceBusClient.DnsIdentity Get start)
                string result = this.fDnsIdentity;
                // *** Start programmer edit section *** (ServiceBusClient.DnsIdentity Get end)

                // *** End programmer edit section *** (ServiceBusClient.DnsIdentity Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ServiceBusClient.DnsIdentity Set start)

                // *** End programmer edit section *** (ServiceBusClient.DnsIdentity Set start)
                this.fDnsIdentity = value;
                // *** Start programmer edit section *** (ServiceBusClient.DnsIdentity Set end)

                // *** End programmer edit section *** (ServiceBusClient.DnsIdentity Set end)
            }
        }

        /// <summary>
        /// ConnectionsLimit.
        /// </summary>
        // *** Start programmer edit section *** (ServiceBusClient.ConnectionsLimit CustomAttributes)
        [DataMember]
        // *** End programmer edit section *** (ServiceBusClient.ConnectionsLimit CustomAttributes)
        public virtual int? ConnectionsLimit
        {
            get
            {
                // *** Start programmer edit section *** (ServiceBusClient.ConnectionsLimit Get start)

                // *** End programmer edit section *** (ServiceBusClient.ConnectionsLimit Get start)
                int? result = this.fConnectionsLimit;
                // *** Start programmer edit section *** (ServiceBusClient.ConnectionsLimit Get end)

                // *** End programmer edit section *** (ServiceBusClient.ConnectionsLimit Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ServiceBusClient.ConnectionsLimit Set start)

                // *** End programmer edit section *** (ServiceBusClient.ConnectionsLimit Set start)
                this.fConnectionsLimit = value;
                // *** Start programmer edit section *** (ServiceBusClient.ConnectionsLimit Set end)

                // *** End programmer edit section *** (ServiceBusClient.ConnectionsLimit Set end)
            }
        }

        /// <summary>
        /// SequentialSent.
        /// </summary>
        // *** Start programmer edit section *** (ServiceBusClient.SequentialSent CustomAttributes)
        [DataMember]
        // *** End programmer edit section *** (ServiceBusClient.SequentialSent CustomAttributes)
        public virtual bool? SequentialSent
        {
            get
            {
                // *** Start programmer edit section *** (ServiceBusClient.SequentialSent Get start)

                // *** End programmer edit section *** (ServiceBusClient.SequentialSent Get start)
                bool? result = this.fSequentialSent;
                // *** Start programmer edit section *** (ServiceBusClient.SequentialSent Get end)

                // *** End programmer edit section *** (ServiceBusClient.SequentialSent Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ServiceBusClient.SequentialSent Set start)

                // *** End programmer edit section *** (ServiceBusClient.SequentialSent Set start)
                this.fSequentialSent = value;
                // *** Start programmer edit section *** (ServiceBusClient.SequentialSent Set end)

                // *** End programmer edit section *** (ServiceBusClient.SequentialSent Set end)
            }
        }
    }
}
