ALTER TABLE Шина ALTER COLUMN Description VARCHAR(MAX) NULL
ALTER TABLE Клиент ALTER COLUMN Description VARCHAR(MAX) NULL
ALTER TABLE Подписка ALTER COLUMN Описание VARCHAR(MAX) NULL
ALTER TABLE ТипСообщения ALTER COLUMN Комментарий VARCHAR(MAX) NULL
