//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ServiceBus
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// MessageWithNotTypedPk.
    /// </summary>
    //  *** Start programmer edit section *** (MessageWithNotTypedPk CustomAttributes)

    //  *** End programmer edit section *** (MessageWithNotTypedPk CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored()]
    [AccessType(ICSSoft.STORMNET.AccessType.@this)]
    public class MessageWithNotTypedPk : NewPlatform.Flexberry.ServiceBus.Message
    {
        
        //  *** Start programmer edit section *** (MessageWithNotTypedPk CustomMembers)
        private object fPrimaryKey;
        //  *** End programmer edit section *** (MessageWithNotTypedPk CustomMembers)

        
        /// <summary>
        /// __PrimaryKey.
        /// </summary>
        //  *** Start programmer edit section *** (MessageWithNotTypedPk.__PrimaryKey CustomAttributes)

        //  *** End programmer edit section *** (MessageWithNotTypedPk.__PrimaryKey CustomAttributes)
        [ICSSoft.STORMNET.NotStored()]
        [NotNull()]
        public override object @__PrimaryKey
        {
            get
            {
                //  *** Start programmer edit section *** (MessageWithNotTypedPk.__PrimaryKey Get)
                return fPrimaryKey;
                //  *** End programmer edit section *** (MessageWithNotTypedPk.__PrimaryKey Get)
            }
            set
            {
                //  *** Start programmer edit section *** (MessageWithNotTypedPk.__PrimaryKey Set)
                fPrimaryKey = value;
                //  *** End programmer edit section *** (MessageWithNotTypedPk.__PrimaryKey Set)
            }
        }
    }
}
