//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ServiceBus
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Queue.
    /// </summary>
    //  *** Start programmer edit section *** (Queue CustomAttributes)

    //  *** End programmer edit section *** (Queue CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored()]
    [AccessType(ICSSoft.STORMNET.AccessType.@this)]
    [View("ListView", new string[] {
            "Recipient as \'Получатель\'",
            "MessageType as \'Тип сообщения\'",
            "Messages as \'Количество сообщений\'"})]
    public class Queue : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private string fRecipient;
        
        private string fMessageType;
        
        private int fMessages;
        
        private string fVHost;
        
        //  *** Start programmer edit section *** (Queue CustomMembers)

        //  *** End programmer edit section *** (Queue CustomMembers)

        
        /// <summary>
        /// Queue name.
        /// </summary>
        //  *** Start programmer edit section *** (Queue.Name CustomAttributes)

        //  *** End programmer edit section *** (Queue.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                //  *** Start programmer edit section *** (Queue.Name Get start)

                //  *** End programmer edit section *** (Queue.Name Get start)
                string result = this.fName;
                //  *** Start programmer edit section *** (Queue.Name Get end)

                //  *** End programmer edit section *** (Queue.Name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Queue.Name Set start)

                //  *** End programmer edit section *** (Queue.Name Set start)
                this.fName = value;
                //  *** Start programmer edit section *** (Queue.Name Set end)

                //  *** End programmer edit section *** (Queue.Name Set end)
            }
        }
        
        /// <summary>
        /// Recipient ID.
        /// </summary>
        //  *** Start programmer edit section *** (Queue.Recipient CustomAttributes)

        //  *** End programmer edit section *** (Queue.Recipient CustomAttributes)
        [StrLen(255)]
        public virtual string Recipient
        {
            get
            {
                //  *** Start programmer edit section *** (Queue.Recipient Get start)

                //  *** End programmer edit section *** (Queue.Recipient Get start)
                string result = this.fRecipient;
                //  *** Start programmer edit section *** (Queue.Recipient Get end)

                //  *** End programmer edit section *** (Queue.Recipient Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Queue.Recipient Set start)

                //  *** End programmer edit section *** (Queue.Recipient Set start)
                this.fRecipient = value;
                //  *** Start programmer edit section *** (Queue.Recipient Set end)

                //  *** End programmer edit section *** (Queue.Recipient Set end)
            }
        }
        
        /// <summary>
        /// Message type ID.
        /// </summary>
        //  *** Start programmer edit section *** (Queue.MessageType CustomAttributes)

        //  *** End programmer edit section *** (Queue.MessageType CustomAttributes)
        [StrLen(255)]
        public virtual string MessageType
        {
            get
            {
                //  *** Start programmer edit section *** (Queue.MessageType Get start)

                //  *** End programmer edit section *** (Queue.MessageType Get start)
                string result = this.fMessageType;
                //  *** Start programmer edit section *** (Queue.MessageType Get end)

                //  *** End programmer edit section *** (Queue.MessageType Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Queue.MessageType Set start)

                //  *** End programmer edit section *** (Queue.MessageType Set start)
                this.fMessageType = value;
                //  *** Start programmer edit section *** (Queue.MessageType Set end)

                //  *** End programmer edit section *** (Queue.MessageType Set end)
            }
        }
        
        /// <summary>
        /// The number of messages in the queue.
        /// </summary>
        //  *** Start programmer edit section *** (Queue.Messages CustomAttributes)

        //  *** End programmer edit section *** (Queue.Messages CustomAttributes)
        public virtual int Messages
        {
            get
            {
                //  *** Start programmer edit section *** (Queue.Messages Get start)

                //  *** End programmer edit section *** (Queue.Messages Get start)
                int result = this.fMessages;
                //  *** Start programmer edit section *** (Queue.Messages Get end)

                //  *** End programmer edit section *** (Queue.Messages Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Queue.Messages Set start)

                //  *** End programmer edit section *** (Queue.Messages Set start)
                this.fMessages = value;
                //  *** Start programmer edit section *** (Queue.Messages Set end)

                //  *** End programmer edit section *** (Queue.Messages Set end)
            }
        }
        
        /// <summary>
        /// The name of VHost.
        /// </summary>
        //  *** Start programmer edit section *** (Queue.VHost CustomAttributes)

        //  *** End programmer edit section *** (Queue.VHost CustomAttributes)
        [StrLen(255)]
        public virtual string VHost
        {
            get
            {
                //  *** Start programmer edit section *** (Queue.VHost Get start)

                //  *** End programmer edit section *** (Queue.VHost Get start)
                string result = this.fVHost;
                //  *** Start programmer edit section *** (Queue.VHost Get end)

                //  *** End programmer edit section *** (Queue.VHost Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Queue.VHost Set start)

                //  *** End programmer edit section *** (Queue.VHost Set start)
                this.fVHost = value;
                //  *** Start programmer edit section *** (Queue.VHost Set end)

                //  *** End programmer edit section *** (Queue.VHost Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ListView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ListView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ListView", typeof(NewPlatform.Flexberry.ServiceBus.Queue));
                }
            }
        }
    }
}
